"""Scenarios for tests/parity/runner.py.

Paths in `files` are relative to the scenario root (home/, project/). Steps:
  ("keys", text)  literal input      ("key", name)  tmux key name (Enter, C-o)
  ("wait", regex[, label])  record input→screen latency under `label`
  ("settle"[, seconds])     wait for a quiet screen   ("snap", name)
  ("write", path, text)     change a file under the scenario root
"""
import sys; sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parents[2] / "tests"))
from upstream_pin import UPSTREAM
import base64
import json
import os
import shutil
from pathlib import Path

MODEL = ["--provider", "openai", "--model", "gpt-5"]
READY = r"gpt-5 • "  # the footer's model line: the editor is mounted
THEME_BAR = json.dumps({**json.loads((Path(__file__).resolve().parents[2] / "packages/coding-agent/src/modes/interactive/theme/dark.json").read_text()), "name": "bar"})
THEME_OTHER = json.dumps({**json.loads(THEME_BAR), "name": "other"})

RESOURCES = {
    "home/.agents/skills/demo/SKILL.md": "---\nname: demo\ndescription: A demo skill for parity tests.\n---\nDo the demo.\n",
    "project/AGENTS.md": "# Project rules\n\nKeep answers short.\n",
}

EXTERNAL_EDITOR = """import pathlib, sys
path = pathlib.Path(sys.argv[1])
print("External editor ready", flush=True)
action = input()
if action == "fail":
    path.write_text("discard this change\\n")
    sys.exit(7)
path.write_text("" if action == "clear" else path.read_text() + " " + action + "\\n")
"""

def typed(word):
    """Type a word one key at a time, timing each key until it is painted."""
    steps = []
    for index in range(1, len(word) + 1):
        steps.append(("keys", word[index - 1]))
        steps.append(("wait", rf"(^|\s){word[:index]}(\s|$)", f"key{index}"))
    return steps

# @ file completion needs fd (pi's fdPath); scenarios that use it put the
# directory of an installed fd on PATH.
FD = shutil.which("fd") or os.path.expanduser("~/.pi/agent/bin/fd")
FD_PATH = {"PATH": os.path.dirname(FD) + ":" + os.environ.get("PATH", "")}

CODE_ANSWER = """Here is the code:

```typescript
interface Point { x: number; y: number }
// Distance between two points.
export function distance(a: Point, b: Point): number {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return Math.sqrt(dx * dx + dy * dy);
}
const origin: Point = { x: 0, y: 0 };
console.log(`distance: ${distance(origin, { x: 3, y: 4 })}`);
```

```python
def fib(n: int) -> int:
    \"\"\"Return the n-th Fibonacci number.\"\"\"
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a
```

END-OF-CODE"""

ANSWER = " ".join(f"word{index}" for index in range(1, 121)) + " END-OF-ANSWER"

# A long Markdown answer for the streaming benchmark: paragraphs, lists,
# emphasis and highlighted code, about 11 KB.
def stream_section(index):
    return (f"## Section {index}\n\nParagraph {index} explains **step {index}** of the plan in plain words, "
            f"with `inline code`, a [link](https://example.com/{index}) and enough text to wrap across the terminal width twice over.\n\n"
            f"- first point of section {index}\n- second point, *emphasised*\n- third point\n\n"
            f"```python\ndef step_{index}(values):\n    return [value * {index} for value in values if value > 0]\n```\n\n")
STREAM_ANSWER = "STREAM-START\n\n" + "".join(stream_section(index) for index in range(1, 31)) + "END-OF-STREAM"
SEARCH_STEPS = [("wait", READY, "startup"), ("wait", "Warning: fd not found", "ready"),
                ("keys", "hello"), ("key", "Enter"), ("wait", "needle two", "answer"),
                ("settle", 0.3), ("keys", "\x1b[102;6u"), ("settle", 0.2),
                ("snap", "open"), ("keys", "needle"), ("settle", 0.2),
                ("snap", "matches"), ("key", "Enter"), ("settle", 0.2),
                ("snap", "next"), ("key", "Escape"), ("settle", 0.2),
                ("snap", "closed")]

SCENARIOS = [
    {
        "name": "fullscreen-startup",
        "args": MODEL + ["--tui-mode", "fullscreen"],
        "files": RESOURCES,
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("snap", "startup"),
                  ("keys", "hello fullscreen"), ("settle", 0.3), ("snap", "typed")],
    },
    {
        "name": "fullscreen-search",
        "args": MODEL + ["--tui-mode", "fullscreen"],
        "files": {**RESOURCES, "home/.pi/agent/settings.json": '{"lastChangelogVersion":"0.87.1"}'},
        "turns": [{"text": "needle one\nmiddle\nneedle two\nend"}],
        "steps": SEARCH_STEPS,
    },
    {
        "name": "fullscreen-search-light",
        "args": MODEL + ["--tui-mode", "fullscreen"],
        "files": {**RESOURCES, "home/.pi/agent/settings.json": '{"theme":"light","lastChangelogVersion":"0.87.1"}'},
        "turns": [{"text": "needle one\nmiddle\nneedle two\nend"}],
        "steps": SEARCH_STEPS,
    },
    {
        "name": "fullscreen-settings",
        "args": MODEL,
        "files": {**RESOURCES, "home/.pi/agent/settings.json": '{"tuiMode":"fullscreen"}'},
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("snap", "startup")],
    },
    {
        "name": "fullscreen-exit",
        "args": MODEL + ["--tui-mode", "fullscreen"],
        "files": RESOURCES,
        "steps": [("wait", READY, "startup"), ("key", "C-d"),
                  ("wait", "shell\\$", "exit"), ("snap", "exit")],
    },
    {
        "name": "fullscreen-turn-exit",
        "args": MODEL + ["--tui-mode", "fullscreen"],
        "files": RESOURCES,
        "turns": [{"text": "A short reply."}],
        "steps": [("wait", READY, "startup"), ("wait", "Warning: fd not found", "ready"),
                  ("settle", 0.3), ("keys", "hello"), ("key", "Enter"),
                  ("wait", "A short reply.", "answer"), ("settle", 0.3),
                  ("key", "C-d"), ("wait", "shell\\$", "exit"), ("snap", "exit")],
    },
    {
        "name": "fullscreen-scroll",
        "args": MODEL + ["--tui-mode", "fullscreen"],
        "files": RESOURCES,
        "turns": [{"text": STREAM_ANSWER}],
        "steps": [("wait", READY, "startup"), ("wait", "Warning: fd not found", "ready"),
                  ("settle", 0.3), ("keys", "hello"), ("key", "Enter"),
                  ("wait", "END-OF-STREAM", "answer"), ("settle", 0.5),
                  ("snap", "bottom"), ("key", "PageUp"), ("settle", 0.2),
                  ("snap", "page-up"), ("key", "PageDown"), ("settle", 0.2),
                  ("snap", "page-down"), ("keys", "\x1b[<64;5;5M"),
                  ("settle", 0.2), ("snap", "wheel-up"),
                  ("key", "Home"), ("settle", 0.2), ("snap", "top"),
                  ("key", "End"), ("settle", 0.2), ("snap", "end")],
    },
    {
        "name": "fullscreen-indicator-light-custom-key",
        "args": MODEL + ["--tui-mode", "fullscreen"],
        "files": {**RESOURCES,
                  "home/.pi/agent/settings.json": json.dumps({"theme": "light"}),
                  "home/.pi/agent/keybindings.json": json.dumps({"tui.altScreen.bottom": "ctrl+g"})},
        "turns": [{"text": STREAM_ANSWER}],
        "steps": [("wait", READY, "startup"), ("wait", "Warning: fd not found", "ready"),
                  ("settle", 0.3), ("keys", "hello"), ("key", "Enter"),
                  ("wait", "END-OF-STREAM", "answer"), ("settle", 0.5),
                  ("key", "PageUp"), ("settle", 0.2), ("snap", "page-up"),
                  ("key", "C-g"), ("settle", 0.2), ("snap", "bottom")],
    },
    {
        "name": "regular-turn-exit",
        "args": MODEL,
        "files": RESOURCES,
        "turns": [{"text": "A short reply."}],
        "steps": [("wait", READY, "startup"), ("wait", "Warning: fd not found", "ready"),
                  ("settle", 0.3), ("keys", "hello"), ("key", "Enter"),
                  ("wait", "A short reply.", "answer"), ("settle", 0.3),
                  ("key", "C-d"), ("wait", "shell\\$", "exit"), ("snap", "exit")],
    },
    {
        "name": "startup",
        "args": MODEL,
        "files": RESOURCES,
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("snap", "startup")],
    },
    {
        "name": "startup-help",
        "args": MODEL,
        "files": RESOURCES,
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("key", "C-o"), ("settle", 0.5), ("snap", "expanded")],
    },
    {
        "name": "trust-interactive",
        "args": MODEL,
        "files": {"project/.pi/settings.json": "{}"},
        "trust_file": True,
        "steps": [("wait", "Trust project folder?", "prompt"), ("settle", 0.2), ("snap", "prompt"),
                  ("key", "Enter"), ("wait", READY, "accepted"), ("settle", 0.2), ("snap", "accepted")],
    },
    {
        "name": "trust-light-256",
        "args": MODEL,
        "files": {"project/.pi/settings.json": "{}", "home/.pi/agent/settings.json": json.dumps({"theme": "light", "terminal": {"trueColor": False}})},
        "trust_file": True,
        "steps": [("wait", "Trust project folder?", "prompt"), ("settle", 0.2), ("snap", "prompt"),
                  ("key", "Enter"), ("wait", READY, "accepted"), ("settle", 0.2), ("snap", "accepted")],
    },
    {
        "name": "trust-session-only",
        "args": MODEL,
        "files": {"project/.pi/settings.json": "{}"},
        "trust_file": True,
        "steps": [("wait", "Trust project folder?", "prompt"), ("key", "Down"), ("key", "Down"),
                  ("settle", 0.2), ("snap", "choice"), ("key", "Enter"),
                  ("wait", READY, "accepted"), ("settle", 0.2), ("snap", "accepted")],
    },
    {
        "name": "trust-decline",
        "args": MODEL,
        "files": {"project/.pi/settings.json": "{}"},
        "trust_file": True,
        "steps": [("wait", "Trust project folder?", "prompt"), ("key", "Down"), ("key", "Down"),
                  ("key", "Down"), ("settle", 0.2), ("snap", "choice"), ("key", "Enter"),
                  ("wait", READY, "declined"), ("settle", 0.2), ("snap", "declined")],
    },
    {
        "name": "trust-command",
        "args": MODEL,
        "files": {"project/.pi/settings.json": "{}", "home/.pi/agent/trust.json": json.dumps({"<root>/project": False})},
        "trust_file": True,
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("keys", "/trust"), ("key", "Enter"),
                  ("wait", "Saved decision: untrusted", "selector"), ("settle", 0.2), ("snap", "selector"),
                  ("key", "Up"), ("key", "Up"), ("key", "Enter"),
                  ("wait", "Saved trust decision: trusted", "saved"), ("settle", 0.2), ("snap", "saved")],
    },
    {
        "name": "trust-command-cancel",
        "args": MODEL,
        "files": {"project/.pi/settings.json": "{}", "home/.pi/agent/trust.json": json.dumps({"<root>/project": False})},
        "trust_file": True,
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("keys", "/trust"), ("key", "Enter"),
                  ("wait", "Saved decision: untrusted", "selector"), ("key", "Escape"),
                  ("settle", 0.2), ("snap", "cancelled")],
    },
    {
        "name": "trust-custom-bindings",
        "args": MODEL,
        "files": {"project/.pi/settings.json": "{}", "home/.pi/agent/trust.json": json.dumps({"<root>/project": False}),
                  "home/.pi/agent/keybindings.json": json.dumps({"tui.select.down": "ctrl+n"})},
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("keys", "/trust"), ("key", "Enter"),
                  ("wait", "Saved decision: untrusted", "selector"), ("key", "Up"), ("key", "Up"),
                  ("key", "Down"), ("settle", 0.2), ("snap", "default-key"),
                  ("key", "C-n"), ("settle", 0.2), ("snap", "custom-key")],
    },
    {
        "name": "trust-on-reload",
        "args": MODEL,
        "trust_file": True,
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("write", "project/.pi/settings.json", "{}"),
                  ("keys", "/reload"), ("key", "Enter"),
                  ("wait", "saved project trust", "reloaded"), ("settle", 0.2), ("snap", "reloaded")],
    },
    {
        "name": "bash-env",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "!env | grep ^PI_ | sort"), ("key", "Enter"),
                  ("wait", r"PI_OFFLINE=1", "bash"), ("settle", 0.5), ("snap", "bash")],
    },
    {
        # upstream BashExecutionComponent: running loader, collapsed preview of
        # the last 20 lines with its expand hint, output without a final
        # newline, and a failing exit code.
        "name": "bash-shapes",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "!sleep 2; echo done"), ("key", "Enter"),
                  ("wait", "Running", "running"), ("snap", "running"),
                  ("wait", r"^ *done", "done"), ("settle", 0.3),
                  ("keys", "!seq 30"), ("key", "Enter"), ("wait", r"^ *30", "seq"), ("settle", 0.3), ("snap", "seq"),
                  ("key", "C-o"), ("settle", 0.5), ("snap", "expanded"), ("key", "C-o"), ("settle", 0.3),
                  ("keys", "!printf tail; exit 3"), ("key", "Enter"), ("wait", r"exit 3\)", "failed"), ("settle", 0.3), ("snap", "failed")],
    },
    {
        # Collapsed tool output and its expand hints (bash and read renderers).
        "name": "tool-previews",
        "args": MODEL,
        "files": {"project/data.txt": "".join(f"line {n}\n" for n in range(1, 41))},
        "turns": [{"tool": {"name": "bash", "arguments": {"command": "seq 40"}}},
                  {"tool": {"name": "read", "arguments": {"path": "data.txt"}}}, {"text": "Both done."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "go"), ("key", "Enter"),
                  ("wait", "Both done", "turn"), ("settle", 0.5), ("snap", "collapsed"),
                  ("key", "C-o"), ("settle", 0.5), ("snap", "expanded")],
    },
    {
        "name": "listing-tool-calls",
        "args": MODEL + ["--tools", "read,bash,edit,write,find,grep,ls"],
        "files": {"project/items/one.txt": "needle one\n", "project/items/two.txt": "other two\n",
                  "project/items/other.md": "no match\n"},
        "turns": [{"tool": {"name": "find", "arguments": {"pattern": "*.txt", "path": "items"}}},
                  {"tool": {"name": "grep", "arguments": {"pattern": "needle", "path": "items"}}},
                  {"tool": {"name": "ls", "arguments": {"path": "items"}}},
                  {"text": "Search complete."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "search"), ("key", "Enter"),
                  ("wait", "Search complete", "turn"), ("settle", 0.5), ("snap", "collapsed")],
    },
    {
        "name": "bash-timeout",
        "args": MODEL,
        "turns": [{"tool": {"name": "bash", "arguments": {"command": "printf ready", "timeout": 5}}}, {"text": "Done."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "run"), ("key", "Enter"),
                  ("wait", "Done.", "turn"), ("settle", 0.5), ("snap", "timed")],
    },
    {
        "name": "bash-truncated",
        "args": MODEL,
        "turns": [{"tool": {"name": "bash", "arguments": {"command": "seq 2101"}}}, {"text": "Done."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "run"), ("key", "Enter"),
                  ("wait", "Done.", "turn"), ("settle", 0.5), ("snap", "truncated")],
    },
    {
        "name": "ls-preview",
        "args": MODEL + ["--tools", "ls"],
        "files": {f"project/items/file-{n:02}.txt": "data\n" for n in range(1, 26)},
        "turns": [{"tool": {"name": "ls", "arguments": {"path": "items"}}}, {"text": "Listed."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "list"), ("key", "Enter"),
                  ("wait", "Listed.", "turn"), ("settle", 0.5), ("snap", "collapsed"),
                  ("key", "C-o"), ("settle", 0.5), ("snap", "expanded")],
    },
    {
        "name": "ls-limit",
        "args": MODEL + ["--tools", "ls"],
        "files": {f"project/items/file-{n:02}.txt": "data\n" for n in range(1, 6)},
        "turns": [{"tool": {"name": "ls", "arguments": {"path": "items", "limit": 3}}}, {"text": "Listed."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "list"), ("key", "Enter"),
                  ("wait", "Listed.", "turn"), ("settle", 0.5), ("snap", "limited")],
    },
    {
        "name": "edit-preview",
        "args": MODEL,
        "files": {"project/note.txt": "alpha\nbeta\n"},
        "turns": [{"tool": {"name": "edit", "arguments": {"path": "note.txt", "edits": [{"oldText": "beta", "newText": "gamma"}]}}},
                  {"text": "Updated."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "update"), ("key", "Enter"),
                  ("wait", "Updated.", "turn"), ("settle", 0.5), ("snap", "edited")],
    },
    {
        "name": "typing",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.5), *typed("parity"), ("settle", 0.3), ("snap", "typed")],
    },
    {
        "name": "hotkeys",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("keys", "/hotkeys"), ("key", "Enter"),
                  ("wait", "Run bash command \\(excluded from context\\)", "hotkeys"), ("settle", 0.3), ("snap", "hotkeys")],
    },
    {
        "name": "hotkeys-custom-binding",
        "args": MODEL,
        "files": {"home/.pi/agent/keybindings.json": json.dumps({"app.model.select": "ctrl+k"})},
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("keys", "/hotkeys"), ("key", "Enter"),
                  ("wait", "Run bash command \\(excluded from context\\)", "hotkeys"), ("settle", 0.3), ("snap", "hotkeys"),
                  ("key", "C-k"), ("wait", "Only showing models", "picker"), ("settle", 0.3), ("snap", "picker")],
    },
    # Editor autocomplete: slash commands (skills rank by bare name), @ after
    # CJK punctuation, and Tab path completion after CJK punctuation.
    {
        "name": "autocomplete-slash",
        "args": MODEL,
        "files": {**RESOURCES, "home/.agents/skills/research-idea/SKILL.md": "---\nname: research-idea\ndescription: Refine an idea.\n---\nRefine.\n"},
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("keys", "/idea"), ("wait", "research-idea", "popup"), ("settle", 0.3), ("snap", "idea"),
                  ("key", "C-u"), ("keys", "/mo"), ("wait", "model", "popup2"), ("settle", 0.3), ("snap", "mo")],
    },
    {
        "name": "autocomplete-at-cjk",
        "args": MODEL,
        "env": FD_PATH,
        "files": {"project/说明.md": "text\n", "project/文档/说明.md": "nested\n", "project/README.md": "readme\n"},
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("keys", "查看，@说"), ("wait", "说明.md", "popup"), ("settle", 0.3), ("snap", "popup"),
                  ("key", "Tab"), ("settle", 0.5), ("snap", "accepted"),
                  ("key", "C-u"), ("keys", "查看@REA"), ("settle", 0.8), ("snap", "letters")],
    },
    {
        "name": "autocomplete-tab-cjk",
        "args": MODEL,
        "files": {"project/文档/说明.md": "nested\n"},
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("keys", "查看。文"), ("key", "Tab"), ("settle", 0.8), ("snap", "directory"),
                  ("keys", "说"), ("key", "Tab"), ("settle", 0.8), ("snap", "file")],
    },
    # Typing latency with a large resumed session on screen (upstream's
    # large-session fixture: ~1000 entries).
    {
        "name": "large-session-typing",
        "args": MODEL + ["--session", "large.jsonl"],
        "files": {"project/large.jsonl": open(str(UPSTREAM / 'packages/coding-agent/test/fixtures/large-session.jsonl')).read()},
        "steps": [("wait", "Continue", "prompt"), ("key", "Enter"), ("wait", READY, "startup"), ("settle", 1.0), *typed("typing"), ("settle", 0.3), ("snap", "typed")],
    },
    # A stored session whose cwd is gone: interactive mode asks (upstream
    # promptForMissingSessionCwd); Cancel exits quietly.
    {
        "name": "session-missing-cwd",
        "args": MODEL + ["--session", "large.jsonl"],
        "files": {"project/large.jsonl": open(str(UPSTREAM / 'packages/coding-agent/test/fixtures/large-session.jsonl')).read()},
        "steps": [("wait", "Continue", "prompt"), ("settle", 0.3), ("snap", "prompt"), ("key", "Down"), ("key", "Enter"), ("settle", 1.0), ("snap", "cancelled")],
    },
    {
        "name": "compaction-status", "args": MODEL,
        "files": {"home/.pi/agent/settings.json": json.dumps({"compaction": {"enabled": False, "keepRecentTokens": 32, "reserveTokens": 1024}})},
        "turns": [{"text": "A longer conversation. " * 120 + "END-OF-TURN"}, {"text": "A compact summary of the conversation.", "chunks": 20, "delay_ms": 100}, {"text": "AFTER-COMPACTION"}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "hi"), ("key", "Enter"),
                  ("wait", "END-OF-TURN", "answered"), ("settle", 0.5), ("keys", "/compact"), ("key", "Enter"),
                  ("wait", "Compacting context", "compacting"), ("snap", "compacting"),
                  ("settle", 3.0), ("snap", "compacted"), ("keys", "continue"), ("key", "Enter"),
                  ("wait", "AFTER-COMPACTION", "continued"), ("settle", 0.5), ("snap", "continued")],
    },
    {
        "name": "compaction-cancel", "args": MODEL,
        "files": {"home/.pi/agent/settings.json": json.dumps({"compaction": {"enabled": False, "keepRecentTokens": 32, "reserveTokens": 1024}})},
        "turns": [{"text": "A longer conversation. " * 120 + "END-OF-TURN"}, {"text": "A compact summary of the conversation.", "chunks": 20, "delay_ms": 100}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "hi"), ("key", "Enter"),
                  ("wait", "END-OF-TURN", "answered"), ("settle", 0.5), ("keys", "/compact"), ("key", "Enter"),
                  ("wait", "Compacting context", "compacting"), ("key", "Escape"),
                  ("wait", "Compaction cancelled", "cancelled"), ("settle", 0.5), ("snap", "cancelled")],
    },
    {
        "name": "retry-status", "args": MODEL,
        "files": {"home/.pi/agent/settings.json": json.dumps({"retry": {"enabled": True, "maxRetries": 2, "baseDelayMs": 3000, "provider": {"maxRetries": 0}}})},
        "turns": [{"status": 500}, {"text": "recovered"}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "hi"), ("key", "Enter"),
                  ("wait", r"Retrying \(1/2\) in 3s", "retry"), ("snap", "retry"),
                  ("wait", r"Retrying \(1/2\) in 2s", "countdown"), ("snap", "countdown"),
                  ("wait", "recovered", "recovered"), ("settle", 0.5), ("snap", "answered")],
    },
    {
        "name": "retry-cancel", "args": MODEL,
        "files": {"home/.pi/agent/settings.json": json.dumps({"retry": {"enabled": True, "maxRetries": 2, "baseDelayMs": 3000, "provider": {"maxRetries": 0}}})},
        "turns": [{"status": 500}, {"text": "should not be requested"}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "hi"), ("key", "Enter"),
                  ("wait", r"Retrying \(1/2\) in 3s", "retry"), ("key", "Escape"),
                  ("settle", 3.5), ("snap", "cancelled")],
    },
    {
        "name": "basic-turn",
        "args": MODEL,
        "turns": [{"text": ANSWER, "chunks": 40, "delay_ms": 10, "usage": {"input": 1200, "output": 150}}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "hello"), ("key", "Enter"),
                  ("wait", r"word1\b", "first-token"), ("snap", "working"), ("wait", "END-OF-ANSWER", "last-token"),
                  ("settle", 0.5), ("snap", "answered")],
    },
    # Streaming benchmark over each CLI's own TLS stack: a long Markdown answer
    # in 500 deltas, paced (about 250 per second) and as fast as the server
    # writes. Bend may take at most 1.25x pi's time to render the last token.
    {
        "name": "stream-paced",
        "args": MODEL, "tls": True, "timeout": 60,
        "turns": [{"text": STREAM_ANSWER, "chunks": 500, "delay_ms": 4}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "stream"), ("key", "Enter"),
                  ("wait", r"STREAM-START", "first-token"), ("wait", "END-OF-STREAM", "last-token"),
                  ("settle", 0.5), ("snap", "answered")],
        "within": {"last-token": 1.25},
    },
    {
        "name": "stream-flood",
        "args": MODEL, "tls": True, "timeout": 60,
        "turns": [{"text": STREAM_ANSWER, "chunks": 500}],
        # The start scrolls away faster than the screen is polled.
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "stream"), ("key", "Enter"),
                  ("wait", "END-OF-STREAM", "last-token"),
                  ("settle", 0.5), ("snap", "answered")],
        "within": {"last-token": 1.25},
    },
    # Highlighted code blocks in an answer, then typing with them on screen.
    {
        "name": "code-answer",
        "args": MODEL,
        "turns": [{"text": CODE_ANSWER}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "code"), ("key", "Enter"),
                  ("wait", "END-OF-CODE", "answer"), ("settle", 0.5), ("snap", "answer"), *typed("more"), ("settle", 0.3), ("snap", "typed")],
    },
    {
        "name": "new-session",
        "args": MODEL,
        "turns": [{"text": "First answer."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "hello"), ("key", "Enter"),
                  ("wait", "First answer.", "answer"), ("settle", 0.5),
                  ("keys", "/new"), ("key", "Enter"),
                  ("wait", "New session started", "new"), ("settle", 0.2), ("snap", "after")],
    },
    {
        "name": "resume-interactive",
        "args": MODEL,
        "turns": [{"text": "First answer."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "hello"), ("key", "Enter"),
                  ("wait", "First answer.", "answer"), ("settle", 0.5),
                  ("keys", "/resume"), ("key", "Enter"),
                  ("wait", "Resume Session", "picker"), ("settle", 0.3), ("snap", "picker"),
                  ("key", "Escape"), ("settle", 0.2), ("snap", "cancelled")],
    },
    {
        "name": "resume-controls", "args": MODEL + ["--session-dir", "sessions"],
        "turns": [{"text": "First resume answer."}, {"text": "After resume controls."}],
        "files": {"project/sessions/discard.jsonl": '{"type": "session", "version": 3, "id": "discard", "timestamp": "2025-01-01T00:00:00Z", "cwd": "<root>/project"}\n{"type": "message", "id": "seed-message", "parentId": null, "timestamp": "2025-01-01T00:00:01Z", "message": {"role": "user", "content": "Delete this old session", "timestamp": 1735689601000}}\n{"type": "session_info", "id": "seed-name", "parentId": "seed-message", "timestamp": "2025-01-01T00:00:02Z", "name": "Delete this old session"}\n',
                  "home/.pi/agent/keybindings.json": json.dumps({"app.session.resume": "ctrl+e"})},
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "active request"), ("key", "Enter"), ("wait", "First resume answer.", "answer"), ("settle", 0.3),
                  ("keys", "preserved draft"), ("key", "C-e"), ("wait", "Resume Session", "picker"), ("settle", 0.3), ("snap", "picker"),
                  ("key", "C-d"), ("wait", "Cannot delete the currently active session", "blocked"), ("settle", 0.3), ("snap", "blocked"),
                  ("keys", "Delete this"), ("settle", 0.3), ("key", "C-d"), ("wait", "Delete session", "confirm"), ("settle", 0.3), ("snap", "confirm"),
                  ("key", "Down"), ("key", "Escape"), ("settle", 0.3), ("snap", "cancelled"),
                  ("key", "C-d"), ("key", "Enter"), ("wait", "Session deleted|Session moved to trash", "deleted"), ("settle", 0.3), ("snap", "deleted"),
                  ("key", "Escape"), ("key", "C-e"), ("wait", "Resume Session", "reopened"), ("keys", "Delete this"),
                  ("wait", "No sessions in current folder", "removed"), ("settle", 0.3), ("snap", "removed"),
                  ("key", "Escape"), ("settle", 0.3), ("snap", "draft"),
                  ("key", "Enter"), ("wait", "After resume controls.", "following"), ("settle", 0.3), ("snap", "following")],
    },
    {
        "name": "resume-rename",
        "args": MODEL,
        "turns": [{"text": "First answer."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "hello"), ("key", "Enter"),
                  ("wait", "First answer.", "answer"), ("settle", 0.5),
                  ("keys", "/resume"), ("key", "Enter"), ("wait", "Resume Session", "picker"),
                  ("key", "C-r"), ("wait", "Rename Session", "rename"), ("settle", 0.2), ("snap", "rename"),
                  ("keys", "Renamed"), ("key", "Enter"), ("wait", "Resume Session", "saved"),
                  ("settle", 0.3), ("snap", "saved"), ("key", "Escape"),
                  ("settle", 0.3), ("snap", "closed"),
                  ("keys", "/resume"), ("key", "Enter"), ("wait", "Resume Session", "reopen"),
                  ("settle", 0.2), ("snap", "reopened")],
    },
    {
        "name": "resume-rename-existing",
        "args": MODEL,
        "turns": [{"text": "First answer."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "hello"), ("key", "Enter"),
                  ("wait", "First answer.", "answer"), ("settle", 0.5),
                  ("keys", "/name Old"), ("key", "Enter"), ("wait", "Session name set: Old", "named"),
                  ("settle", 0.2), ("keys", "/resume"), ("key", "Enter"),
                  ("wait", "Resume Session", "picker"), ("key", "C-r"),
                  ("wait", "Rename Session", "rename"), ("keys", "X"), ("key", "Enter"),
                  ("wait", "Resume Session", "saved"), ("settle", 0.3), ("snap", "saved")],
    },
    {
        "name": "clone-session",
        "args": MODEL,
        "turns": [{"text": "First answer."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "hello"), ("key", "Enter"),
                  ("wait", "First answer.", "answer"), ("settle", 0.5),
                  ("keys", "/clone"), ("key", "Enter"),
                  ("wait", "Cloned to new session", "clone"), ("settle", 0.2), ("snap", "after")],
    },
    {
        "name": "clone-empty-error",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("keys", "/clone"), ("key", "Enter"),
                  ("wait", "This session has not been saved yet", "error"), ("settle", 0.3), ("snap", "after")],
    },
    {
        "name": "thinking-invalid-error",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("keys", "/thinking bogus"), ("key", "Enter"),
                  ("wait", "Error:", "error"), ("settle", 0.3), ("snap", "after")],
    },
    {
        "name": "thinking-selector",
        "args": MODEL,
        "env": FD_PATH,
        "steps": [("wait", READY, "startup"), ("settle", 1.0),
                  ("keys", "/thinking"), ("key", "Enter"), ("wait", "Thinking Level", "open"),
                  ("settle", 0.2), ("snap", "open"),
                  ("keys", "high"), ("settle", 0.2), ("snap", "filtered"),
                  ("key", "Enter"), ("wait", "Thinking level: high", "selected"),
                  ("settle", 0.2), ("snap", "selected"),
                  ("keys", "/thinking"), ("key", "Enter"), ("wait", "Thinking Level", "reopen"),
                  ("key", "C-s"), ("wait", "Default thinking level:", "saved"),
                  ("settle", 0.2), ("snap", "saved")],
    },
    {
        "name": "model-command-cached-match",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "/model openai/gpt-5"), ("key", "Enter"), ("settle", 0.1),
                  ("key", "Enter"),
                  ("wait", "Model: gpt-5", "selected"), ("settle", 0.2), ("snap", "selected")],
    },
    {
        "name": "model-command-cache-miss",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "/model no-such-model"), ("key", "Enter"),
                  ("wait", "No matching models", "picker"), ("settle", 0.2), ("snap", "picker")],
    },
    {
        "name": "login-key-paste", "args": MODEL, "env": FD_PATH,
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/login"), ("key", "Enter"), ("settle", 0.2),
                  ("key", "Down"), ("key", "Enter"), ("settle", 0.2),
                  ("keys", "OpenAI"), ("settle", 0.2), ("key", "Enter"),
                  ("wait", "Enter OpenAI API key", "prompt"), ("snap", "prompt"),
                  ("keys", "\x1b[200~sk-"), ("keys", "parity\n"), ("keys", "new\x1b[201~"),
                  ("key", "Left"), ("key", "Left"), ("key", "BSpace"), ("key", "End"), ("keys", "!"),
                  ("key", "Enter"), ("wait", "Saved API key for OpenAI", "saved"),
                  ("settle", 0.3), ("snap", "saved")],
    },
    {
        "name": "login-api-key",
        "args": MODEL,
        "env": FD_PATH,
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "/login"), ("key", "Enter"), ("settle", 0.2), ("snap", "method"),
                  ("key", "Down"), ("key", "Enter"), ("settle", 0.2), ("snap", "providers"),
                  ("keys", "OpenAI"), ("settle", 0.2), ("snap", "filtered"),
                  ("key", "Enter"), ("wait", "Enter OpenAI API key", "prompt"), ("snap", "prompt"),
                  ("keys", "sk-parity-new"), ("settle", 0.1), ("snap", "entered"),
                  ("key", "Enter"), ("settle", 0.3), ("snap", "saved")],
    },
    {
        "name": "scoped-models-selector",
        "args": MODEL,
        "env": FD_PATH,
        "steps": [("wait", READY, "startup"), ("settle", 1.0),
                  ("keys", "/scoped-models"), ("key", "Enter"),
                  ("wait", "Model Configuration", "open"), ("settle", 0.3), ("snap", "open"),
                  ("keys", "gpt-5-mini"), ("settle", 0.2), ("snap", "filtered"),
                  ("key", "Enter"), ("settle", 0.2), ("snap", "toggled"),
                  ("key", "C-s"), ("wait", "Model selection saved to settings", "saved"),
                  ("settle", 0.2), ("snap", "saved"),
                  ("key", "Escape"), ("settle", 0.2), ("snap", "closed"),
                  ("key", "C-p"), ("settle", 0.2), ("snap", "cycled")],
    },
    {
        "name": "scoped-models-controls",
        "args": MODEL,
        "env": FD_PATH,
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/scoped-models"), ("key", "Enter"),
                  ("wait", "Model Configuration", "open"),
                  ("key", "C-x"), ("settle", 0.2), ("snap", "cleared"),
                  ("key", "C-a"), ("settle", 0.2), ("snap", "enabled"),
                  ("key", "C-p"), ("settle", 0.2), ("snap", "provider"),
                  ("key", "Escape"), ("settle", 0.2), ("snap", "closed")],
    },
    {
        "name": "tool-call",
        "args": MODEL,
        "turns": [{"tool": {"name": "bash", "arguments": {"command": "echo tool-output"}}, "start_delay_ms": 1000}, {"text": "Tool finished."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "run it"), ("key", "Enter"),
                  ("wait", "Working", "working"), ("snap", "working"),
                  ("wait", "Tool finished", "turn"), ("settle", 0.5), ("snap", "tool")],
    },
    {
        "name": "bash-preview-wrapped",
        "args": MODEL,
        "env": FD_PATH,
        "turns": [{"tool": {"name": "bash", "arguments": {"command": "python3 -c 'for n in range(1, 13): print(f\"line{n:02} \" + \"x\" * 110)'"}}},
                  {"text": "Preview done."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "show the output"), ("key", "Enter"),
                  ("wait", "Preview done", "done"), ("settle", 0.3), ("snap", "preview")],
    },
    {
        # upstream handleSessionCommand: counts, cached/uncached prompt split
        # and cost after two turns (the second with cache reads).
        "name": "session-info",
        "args": MODEL,
        "turns": [{"text": "First.", "usage": {"input": 1500, "output": 20}},
                  {"text": "Second.", "usage": {"input": 1500, "output": 40, "cacheRead": 1200}}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "one"), ("key", "Enter"), ("wait", "First\\.", "first"), ("settle", 0.3),
                  ("keys", "two"), ("key", "Enter"), ("wait", "Second\\.", "second"), ("settle", 0.3),
                  ("keys", "/session"), ("key", "Enter"), ("wait", "Session Info", "info"), ("settle", 0.3), ("snap", "info")],
    },
    {
        "name": "fork-picker", "args": MODEL,
        "turns": [{"text": "First answer."}, {"text": "Second answer."}, {"text": "Fork answer."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "/fork"), ("key", "Enter"), ("wait", "No messages to fork from", "empty"), ("snap", "empty"),
                  ("keys", "first prompt"), ("key", "Enter"), ("wait", "First answer.", "first"), ("settle", 0.3),
                  ("keys", "second prompt"), ("key", "Enter"), ("wait", "Second answer.", "second"), ("settle", 0.3),
                  ("keys", "/fork"), ("key", "Enter"), ("wait", "Fork from Message", "picker"), ("settle", 0.2), ("snap", "picker"),
                  ("key", "Up"), ("settle", 0.2), ("snap", "older"),
                  ("key", "Up"), ("settle", 0.2), ("snap", "wrapped"),
                  ("key", "Down"), ("key", "Enter"), ("wait", "Forked to new session", "forked"), ("settle", 0.3), ("snap", "forked"),
                  ("keys", " edited"), ("key", "Enter"), ("wait", "Fork answer.", "answer"), ("settle", 0.3), ("snap", "answer")],
    },
    {
        "name": "copy-key", "args": MODEL, "turns": [{"text": "Copy café 日本語."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("key", "C-x"), ("wait", "No agent messages to copy yet", "empty"), ("snap", "empty"),
                  ("keys", "hello"), ("key", "Enter"), ("wait", "Copy café 日本語.", "answer"), ("settle", 0.3),
                  ("keys", "keep this draft"), ("key", "C-x"),
                  ("wait", "Copied last agent message", "copied"), ("settle", 0.2), ("snap", "copied")],
    },
    {
        "name": "external-editor", "args": MODEL,
        "env": {"VISUAL": "/missing/visual", "EDITOR": "/missing/editor"},
        "files": {"project/external-editor.py": EXTERNAL_EDITOR,
                  "home/.pi/agent/settings.json": json.dumps({"externalEditor": "python3 external-editor.py"})},
        "turns": [{"text": "First editor answer."}, {"text": "Second editor answer."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "hello from"), ("key", "C-g"), ("wait", "External editor ready", "opened"), ("snap", "external"),
                  ("keys", "editor"), ("key", "Enter"), ("wait", "hello from editor", "resumed"), ("settle", 0.3), ("snap", "edited"),
                  ("key", "Enter"), ("wait", "First editor answer.", "first"), ("settle", 0.3),
                  ("keys", "preserved draft"), ("key", "C-g"), ("wait", "External editor ready", "failed-open"),
                  ("keys", "fail"), ("key", "Enter"), ("wait", READY, "failed-resume"), ("settle", 0.3), ("snap", "failed"),
                  ("key", "C-g"), ("wait", "External editor ready", "clear-open"),
                  ("keys", "clear"), ("key", "Enter"), ("wait", READY, "clear-resume"), ("settle", 0.3), ("snap", "empty"),
                  ("keys", "second prompt"), ("key", "Enter"), ("wait", "Second editor answer.", "second"), ("settle", 0.3), ("snap", "answer")],
    },
    {
        "name": "external-editor-env-key", "args": MODEL,
        "env": {"VISUAL": "", "EDITOR": "python3 external-editor.py"},
        "files": {"project/external-editor.py": EXTERNAL_EDITOR,
                  "home/.pi/agent/keybindings.json": json.dumps({"app.editor.external": "ctrl+e"})},
        "turns": [{"text": "Edited answer."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "initial"), ("key", "C-e"), ("wait", "External editor ready", "opened"),
                  ("keys", "changed"), ("key", "Enter"), ("wait", "initial changed", "resumed"), ("settle", 0.3), ("snap", "edited"),
                  ("key", "Enter"), ("wait", "Edited answer.", "answer"), ("settle", 0.3), ("snap", "answer")],
    },
    {
        "name": "external-editor-stream", "args": MODEL,
        "env": {"VISUAL": "python3 external-editor.py", "EDITOR": "/missing/editor"},
        "files": {"project/external-editor.py": EXTERNAL_EDITOR},
        "turns": [{"text": "Streaming answer. " * 40 + "EDITOR-STREAM-DONE", "chunks": 100, "delay_ms": 20},
                  {"text": "After editor answer."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "first prompt"), ("key", "Enter"), ("wait", "Streaming answer", "streaming"),
                  ("keys", "next"), ("key", "C-g"), ("wait", "External editor ready", "opened"),
                  ("settle", 2.5), ("keys", "prompt"), ("key", "Enter"),
                  ("wait", "EDITOR-STREAM-DONE", "resumed"), ("settle", 0.3), ("snap", "edited"),
                  ("key", "Enter"), ("wait", "After editor answer.", "answer"), ("settle", 0.3), ("snap", "answer")],
    },
    {
        "name": "session-keys", "args": MODEL, "turns": [{"text": "First answer."}, {"text": "New answer."}],
        "files": {"home/.pi/agent/keybindings.json": json.dumps({"app.session.new": "ctrl+n", "app.session.tree": "ctrl+e", "app.session.fork": "ctrl+f", "app.session.resume": "ctrl+r"})},
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "hello"), ("key", "Enter"), ("wait", "First answer.", "answer"), ("settle", 0.3),
                  ("key", "C-e"), ("wait", "Session Tree", "tree"), ("settle", 0.3), ("snap", "tree"), ("key", "Escape"), ("settle", 0.2),
                  ("key", "C-f"), ("wait", "Fork from Message", "fork"), ("settle", 0.3), ("snap", "fork"), ("key", "Escape"), ("settle", 0.2),
                  ("key", "C-r"), ("wait", "Resume Session", "resume"), ("settle", 0.3), ("snap", "resume"),
                  ("key", "Escape"), ("settle", 0.2), ("keys", "preserved draft"), ("key", "C-n"),
                  ("wait", "New session started", "new"), ("settle", 0.3), ("snap", "new"),
                  ("keys", "new prompt"), ("key", "Enter"), ("wait", "New answer.", "new-answer"), ("settle", 0.3), ("snap", "new-answer")],
    },
    {
        "name": "tree-tools", "args": MODEL,
        "turns": [{"tool": {"name": "read", "arguments": {"path": "note.txt", "offset": 2, "limit": 2}}},
                  {"tool": {"name": "bash", "arguments": {"command": "printf tree-command"}}},
                  {"text": "Tree tools done."}, {"text": "After tree tools."}],
        "files": {"project/note.txt": "first\nsecond\nthird\nfourth\n",
                  "home/.pi/agent/keybindings.json": json.dumps({"app.session.tree": "ctrl+e"})},
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "use tools"), ("key", "Enter"), ("wait", "Tree tools done.", "answer"), ("settle", 0.3),
                  ("keys", "preserved draft"), ("key", "C-e"), ("wait", "Session Tree", "tree"),
                  ("wait", r"\[read: note.txt:2-3\]", "read"), ("wait", r"\[bash: printf tree-command\]", "bash"),
                  ("settle", 0.3), ("snap", "tree"), ("key", "Up"), ("key", "C-x"),
                  ("wait", "Copied selected message to clipboard", "copied"), ("settle", 0.3), ("snap", "copied"),
                  ("key", "C-t"), ("settle", 0.3), ("snap", "no-tools"), ("key", "C-d"),
                  ("settle", 0.3), ("snap", "restored"), ("key", "Escape"), ("settle", 0.3), ("snap", "draft"),
                  ("key", "Enter"), ("wait", "After tree tools.", "following"), ("settle", 0.3), ("snap", "following")],
    },
    {
        "name": "tree-labels", "args": MODEL,
        "turns": [{"text": "Label this answer."}, {"text": "After label answer."}],
        "files": {"home/.pi/agent/keybindings.json": json.dumps({"app.session.tree": "ctrl+e"})},
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "first request"), ("key", "Enter"), ("wait", "Label this answer.", "answer"), ("settle", 0.3),
                  ("keys", "preserved draft"), ("key", "C-e"), ("wait", "Session Tree", "tree"), ("settle", 0.3),
                  ("key", "L"), ("wait", r"Label \(empty to remove\)", "label"), ("settle", 0.3), ("snap", "label"),
                  ("keys", "  project  "), ("key", "C-Left"), ("key", "C-Right"), ("key", "C-e"), ("settle", 0.3), ("snap", "typed"), ("key", "Enter"),
                  ("wait", "[project]", "saved"), ("settle", 0.3), ("snap", "saved"),
                  ("key", "Escape"), ("key", "C-e"), ("wait", "[project]", "reopened"), ("settle", 0.3), ("snap", "reopened"),
                  ("key", "L"), ("wait", r"Label \(empty to remove\)", "edit"), ("key", "C-e"), ("keys", " changed"),
                  ("key", "Escape"), ("settle", 0.3), ("snap", "cancelled"),
                  ("key", "L"), ("wait", r"Label \(empty to remove\)", "remove"), ("key", "C-e"), ("key", "C-u"), ("key", "Enter"),
                  ("settle", 0.3), ("snap", "removed"), ("key", "Escape"), ("key", "C-e"),
                  ("wait", "Session Tree", "unlabeled"), ("settle", 0.3), ("snap", "unlabeled"), ("key", "Escape"),
                  ("settle", 0.3), ("snap", "draft"), ("key", "Enter"), ("wait", "After label answer.", "following"),
                  ("settle", 0.3), ("snap", "following")],
    },
    {
        "name": "tree-controls", "args": MODEL,
        "turns": [{"text": "First answer."}, {"text": "Following answer."}],
        "files": {"home/.pi/agent/keybindings.json": json.dumps({"app.session.tree": "ctrl+e"})},
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "first request"), ("key", "Enter"), ("wait", "First answer.", "answer"), ("settle", 0.3),
                  ("keys", "preserved draft"), ("key", "C-e"), ("wait", "Session Tree", "tree"), ("settle", 0.3), ("snap", "tree"),
                  ("key", "C-l"), ("wait", "No entries found", "empty"), ("settle", 0.3), ("snap", "empty"),
                  ("key", "C-a"), ("key", "Up"), ("settle", 0.3), ("snap", "all"),
                  ("key", "C-x"), ("wait", "Copied selected message to clipboard", "copied"), ("settle", 0.3), ("snap", "copied"),
                  ("key", "Escape"), ("settle", 0.3), ("snap", "draft"),
                  ("key", "Enter"), ("wait", "Following answer.", "following"), ("settle", 0.3), ("snap", "following")],
    },
    {
        "name": "copy",
        "args": MODEL,
        "turns": [{"text": "Copy me."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/copy"), ("key", "Enter"),
                  ("wait", "No agent messages to copy yet", "empty"), ("snap", "empty"),
                  ("keys", "hello"), ("key", "Enter"),
                  ("wait", "Copy me.", "answer"), ("settle", 0.5),
                  ("keys", "/copy"), ("key", "Enter"),
                  ("wait", "Copied last agent message", "copied"), ("snap", "copied")],
    },
    {
        "name": "settings",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/settings"), ("key", "Enter"),
                  ("wait", "Auto-compact", "panel"), ("settle", 0.2), ("snap", "panel"),
                  ("key", "Enter"), ("wait", r"Auto-compact\s+false", "changed"),
                  ("settle", 0.2), ("snap", "changed"),
                  ("key", "Escape"), ("settle", 0.2), ("snap", "closed")],
    },
    {
        "name": "settings-terminal-preferences", "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "/settings"), ("key", "Enter"), ("settle", 0.3),
                  ("keys", "hardware"), ("settle", 0.2), ("snap", "cursor-off"),
                  ("key", "Enter"), ("settle", 0.2), ("snap", "cursor-on"),
                  ("key", "Escape"), ("settle", 0.2),
                  ("keys", "/settings"), ("key", "Enter"), ("settle", 0.3),
                  ("keys", "clear on shrink"), ("settle", 0.2), ("snap", "clear-off"),
                  ("key", "Enter"), ("settle", 0.2), ("snap", "clear-on"),
                  ("key", "Escape"), ("settle", 0.2),
                  ("keys", "typed with live cursor"), ("settle", 0.2), ("snap", "editor")],
    },
    {
        "name": "settings-theme",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/settings"), ("key", "Enter"),
                  ("wait", "Auto-compact", "panel"),
                  ("keys", "Theme"), ("settle", 0.2), ("snap", "filtered"),
                  ("key", "Enter"), ("settle", 0.2), ("snap", "theme-menu"),
                  ("key", "Down"), ("settle", 0.2), ("snap", "preview"),
                  ("key", "Escape"), ("settle", 0.2), ("snap", "cancelled")],
    },
    {
        "name": "settings-theme-save",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/settings"), ("key", "Enter"), ("wait", "Auto-compact", "panel"),
                  ("keys", "Theme"), ("key", "Enter"), ("key", "Down"),
                  ("key", "Enter"), ("settle", 0.2), ("snap", "saved")],
    },
    {
        "name": "settings-theme-automatic",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/settings"), ("key", "Enter"), ("wait", "Auto-compact", "panel"),
                  ("keys", "Theme"), ("key", "Enter"), ("key", "Up"),
                  ("key", "Enter"), ("settle", 0.2), ("snap", "automatic"),
                  ("key", "Down"), ("key", "Down"), ("key", "Enter"),
                  ("settle", 0.2), ("snap", "saved")],
    },
    {
        "name": "loaded-theme-resources",
        "args": MODEL,
        "files": {"home/.pi/agent/themes/foo.json": THEME_BAR},
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("snap", "compact"),
                  ("key", "C-o"), ("settle", 0.2), ("snap", "expanded"),
                  ("key", "C-o"), ("settle", 0.2),
                  ("write", "home/.pi/agent/themes/foo.json", THEME_OTHER),
                  ("keys", "/reload"), ("key", "Enter"),
                  ("wait", "Reloaded", "reloaded"), ("settle", 0.3), ("snap", "refreshed")],
    },
    {
        "name": "loaded-theme-quiet",
        "args": MODEL,
        "files": {"home/.pi/agent/settings.json": '{"quietStartup":true}',
                  "home/.pi/agent/themes/foo.json": THEME_BAR},
        "steps": [("wait", READY, "startup"), ("settle", 0.3), ("snap", "quiet")],
    },
    {
        "name": "settings-theme-custom-name",
        "args": MODEL,
        "files": {"home/.pi/agent/themes/foo.json": THEME_BAR},
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/settings"), ("key", "Enter"), ("wait", "Auto-compact", "panel"),
                  ("keys", "Theme"), ("key", "Enter"), ("settle", 0.2), ("snap", "themes")],
    },
    {
        "name": "settings-theme-marked",
        "args": MODEL,
        "files": {"home/.pi/agent/settings.json": '{"theme":"light"}',
                  "home/.pi/agent/themes/other.json": THEME_OTHER},
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/settings"), ("key", "Enter"), ("wait", "Auto-compact", "panel"),
                  ("keys", "Theme"), ("key", "Enter"), ("settle", 0.2), ("snap", "marked"),
                  ("key", "Down"), ("settle", 0.2), ("snap", "moved")],
    },
    {
        "name": "settings-model-thinking",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/settings"), ("key", "Enter"), ("wait", "Auto-compact", "panel"),
                  ("keys", "Default thinking level per model"), ("settle", 0.2), ("snap", "row"),
                  ("key", "Enter"), ("settle", 0.2), ("snap", "models"),
                  ("key", "Enter"), ("settle", 0.2), ("snap", "levels")],
    },
    {
        "name": "settings-model-thinking-save",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/settings"), ("key", "Enter"), ("wait", "Auto-compact", "panel"),
                  ("keys", "Default thinking level per model"), ("key", "Enter"),
                  ("key", "Enter"), ("key", "Down"), ("key", "Down"),
                  ("key", "Enter"), ("settle", 0.2), ("snap", "models-again"),
                  ("key", "Escape"), ("settle", 0.2), ("snap", "saved")],
    },
    {
        "name": "settings-model-thinking-current",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/settings"), ("key", "Enter"), ("wait", "Auto-compact", "panel"),
                  ("keys", "Default thinking level per model"), ("key", "Enter"), ("key", "Enter"),
                  ("key", "Down"), ("key", "Down"), ("key", "Down"), ("key", "Enter"),
                  ("settle", 0.2), ("snap", "high"),
                  ("key", "Enter"), ("key", "Down"), ("key", "Enter"),
                  ("key", "Escape"), ("settle", 0.2), ("snap", "cleared")],
    },
    {
        "name": "settings-model-thinking-marked",
        "args": MODEL,
        "files": {"home/.pi/agent/settings.json": '{"modelThinkingLevels":{"openai/gpt-5":"medium"}}'},
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("keys", "/settings"), ("key", "Enter"), ("wait", "Auto-compact", "panel"),
                  ("keys", "Default thinking level per model"), ("key", "Enter"), ("key", "Enter"),
                  ("settle", 0.2), ("snap", "marked"),
                  ("key", "Down"), ("settle", 0.2), ("snap", "moved")],
    },
    {
        # On exit pi leaves its last frame, footer included, above the shell prompt.
        "name": "exit",
        "args": MODEL,
        "files": RESOURCES,
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("key", "C-d"), ("settle", 1.0), ("snap", "exited")],
    },
    {
        # /changelog lists every entry, oldest first; the screen shows the newest.
        "name": "changelog-command",
        "args": MODEL,
        "timeout": 60,
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "/changelog"), ("key", "Enter"),
                  ("wait", "outdated Claude Code version", "changelog"), ("settle", 1.0), ("snap", "changelog")],
    },
    {
        # After an update, the entries newer than lastChangelogVersion are shown.
        "name": "whats-new",
        "args": MODEL,
        "files": {"home/.pi/agent/settings.json": json.dumps({"lastChangelogVersion": "0.86.0"})},
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("snap", "startup")],
    },
    {
        # /reload picks up edited context files and skills for the next request.
        "name": "reload",
        "args": MODEL,
        "files": RESOURCES,
        "turns": [{"text": "Reloaded answer."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5),
                  ("write", "project/AGENTS.md", "# Project rules\n\nAnswer in haiku.\n"),
                  ("write", "home/.agents/skills/extra/SKILL.md", "---\nname: extra\ndescription: Another skill.\n---\nMore.\n"),
                  ("keys", "/reload"), ("key", "Enter"), ("wait", "Reloaded keybindings", "reload"), ("settle", 0.5), ("snap", "reloaded"),
                  ("keys", "hi"), ("key", "Enter"), ("wait", "Reloaded answer", "turn"), ("settle", 0.5), ("snap", "answered")],
    },
    {
        "name": "shortcuts",
        "args": ["--provider", "openai", "--models", "gpt-5,gpt-5-mini"],
        "steps": [("wait", r"gpt-5 • ", "startup"), ("settle", 0.5),
                  ("key", "S-Tab"), ("settle", 0.5), ("snap", "thinking-cycled"),
                  ("key", "C-p"), ("settle", 0.5), ("snap", "model-cycled")],
    },
    {
        # Pi uses the target model's saved level, then the global default,
        # before retaining the current level during a model switch.
        "name": "model-cycle-default-thinking",
        "args": ["--provider", "openai", "--models", "gpt-5,gpt-5-mini", "--thinking", "low"],
        "files": {"home/.pi/agent/settings.json": json.dumps({
            "defaultProvider": "openai", "defaultModel": "gpt-5", "defaultThinkingLevel": "high"})},
        "steps": [("wait", r"gpt-5 • low", "startup"), ("settle", 0.3), ("snap", "before"),
                  ("key", "C-p"), ("wait", r"gpt-5-mini • high", "cycled"),
                  ("settle", 0.3), ("snap", "after")],
    },
    {
        "name": "model-selector",
        "args": ["--provider", "openai", "--models", "gpt-5,gpt-5-mini"],
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "/model"), ("key", "Enter"), ("settle", 0.3),
                  ("snap", "open"), ("key", "Down"), ("settle", 0.2),
                  ("snap", "browsed"), ("keys", "mini"), ("settle", 0.2),
                  ("snap", "filtered")],
    },
    {
        "name": "model-selector-save",
        "args": ["--provider", "openai", "--models", "gpt-5,gpt-5-mini"],
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "/model"), ("key", "Enter"), ("settle", 0.3),
                  ("key", "Down"), ("key", "C-s"),
                  ("wait", "Default model: openai/gpt-5-mini", "saved"),
                  ("settle", 0.3), ("snap", "saved")],
    },
    {
        "name": "model-selector-all-filter",
        "args": MODEL,
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "/model"), ("key", "Enter"), ("settle", 0.3),
                  ("key", "Down"), ("key", "Down"), ("settle", 0.2),
                  ("snap", "browsed"), ("keys", "gpt"), ("settle", 0.2),
                  ("snap", "filtered")],
    },
    {
        "name": "model-selector-custom-save",
        "args": ["--provider", "openai", "--models", "gpt-5,gpt-5-mini"],
        "files": {"home/.pi/agent/keybindings.json": json.dumps({"app.models.save": "ctrl+r"})},
        "steps": [("wait", READY, "startup"), ("settle", 0.3),
                  ("keys", "/model"), ("key", "Enter"), ("settle", 0.3),
                  ("key", "Down"), ("key", "C-s"), ("settle", 0.2),
                  ("snap", "default-key-ignored"), ("key", "C-r"),
                  ("wait", "Default model: openai/gpt-5-mini", "saved"),
                  ("settle", 0.3), ("snap", "saved")],
    },
    {
        # models.json provider headers reach the request (upstream prepareRequest).
        "name": "provider-headers",
        "args": MODEL,
        "provider": {"headers": {"X-Team": "t1"}},
        "turns": [{"text": "Headers seen."}],
        "steps": [("wait", READY, "startup"), ("settle", 0.5), ("keys", "hi"), ("key", "Enter"),
                  ("wait", "Headers seen", "turn"), ("settle", 0.5), ("snap", "answered")],
    },
    {
        "name": "print-turn",
        "process": True,
        "args": MODEL + ["-p", "hello"],
        "turns": [{"text": "Printed answer.", "chunks": 3, "usage": {"input": 900, "output": 20}}],
        "steps": [],
    },
    {
        "name": "print-tool",
        "process": True,
        "args": MODEL + ["-p", "run it"],
        "turns": [{"tool": {"name": "bash", "arguments": {"command": "echo tool-output"}}}, {"text": "Tool finished."}],
        "steps": [],
    },
    {
        # The settings' shellCommandPrefix reaches the built-in bash tool
        # (upstream AgentSession._buildRuntime).
        "name": "print-tool-settings",
        "process": True,
        "args": MODEL + ["-p", "run it"],
        "files": {"home/.pi/agent/settings.json": json.dumps({"shellCommandPrefix": "export PI_PARITY_PREFIX=applied"})},
        "turns": [{"tool": {"name": "bash", "arguments": {"command": "echo prefix:$PI_PARITY_PREFIX"}}}, {"text": "Tool finished."}],
        "steps": [],
    },
    {
        # The JSON event stream of one tool turn (timestamps and ids normalised).
        "name": "json-turn",
        "process": True,
        "args": MODEL + ["--mode", "json", "run it"],
        "turns": [{"tool": {"name": "bash", "arguments": {"command": "echo tool-output"}}}, {"text": "Tool finished."}],
        "steps": [],
    },
    {"name": "cli-help", "process": True, "args": ["--help"], "steps": []},
    {"name": "cli-version", "process": True, "args": ["--version"], "steps": []},
    {"name": "cli-list-models", "process": True, "args": ["--list-models"], "steps": []},
    {"name": "cli-list-models-search", "process": True, "args": ["--list-models", "gpt-5"], "steps": []},
    {"name": "cli-unknown-model", "process": True, "args": ["--provider", "openai", "--model", "nope", "-p", "hi"], "steps": []},
    {"name": "cli-unknown-provider", "process": True, "args": ["--provider", "nosuch", "--model", "x", "-p", "hi"], "steps": []},
    {"name": "cli-no-prompt-print", "process": True, "args": MODEL + ["-p"], "steps": []},
    {"name": "print-thinking-high", "process": True, "args": MODEL + ["--thinking", "high", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-model-suffix", "process": True, "args": ["--provider", "openai", "--model", "gpt-5:low", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-no-tools", "process": True, "args": MODEL + ["--no-tools", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-tools-subset", "process": True, "args": MODEL + ["--tools", "read,ls,grep", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-system-prompt", "process": True, "args": MODEL + ["--system-prompt", "You are terse.", "--append-system-prompt", "Always answer in English.", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-context-skills", "process": True, "args": MODEL + ["-p", "hi"], "files": RESOURCES, "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-file-arg", "process": True, "args": MODEL + ["-p", "@notes.txt", "summarise"], "files": {"project/notes.txt": "line one\nline two\n"}, "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-continue", "process": True, "before": [MODEL + ["-p", "first"]], "args": MODEL + ["-c", "-p", "second"],
     "turns": [{"text": "first answer"}, {"text": "second answer"}], "steps": []},
    {"name": "print-read-tool", "process": True, "args": MODEL + ["-p", "read it"], "files": {"project/data.txt": "alpha\nbeta\n"},
     "turns": [{"tool": {"name": "read", "arguments": {"path": "data.txt"}}}, {"text": "Read done."}], "steps": []},
    {"name": "print-http-400", "process": True, "args": MODEL + ["-p", "hi"],
     "turns": [{"status": 400, "error": {"error": {"message": "Invalid request: bad field", "type": "invalid_request_error"}}}], "steps": []},
    {"name": "print-retry-500", "process": True, "args": MODEL + ["-p", "hi"],
     "files": {"home/.pi/agent/settings.json": json.dumps({"retry": {"enabled": True, "maxRetries": 2, "baseDelayMs": 10}})},
     "turns": [{"status": 500}, {"text": "recovered"}], "steps": []},
    {"name": "print-failed", "process": True, "args": MODEL + ["-p", "hi"],
     "files": {"home/.pi/agent/settings.json": json.dumps({"retry": {"enabled": False}})},
     "turns": [{"failed": {"code": "server_error", "message": "boom"}}], "steps": []},
    {"name": "print-name", "process": True, "args": MODEL + ["--name", "Parity run", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-session-id", "process": True, "args": MODEL + ["--session-id", "parity-session", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-no-session", "process": True, "args": MODEL + ["--no-session", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-exclude-tools", "process": True, "args": MODEL + ["--exclude-tools", "bash,write", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-dash-message", "process": True, "args": MODEL + ["-p", "--", "- a point"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-two-messages", "process": True, "args": MODEL + ["-p", "first", "second"], "turns": [{"text": "one"}, {"text": "two"}], "steps": []},
    {"name": "print-template", "process": True, "args": MODEL + ["-p", "/review src/app.ts carefully"],
     "files": {"home/.pi/agent/prompts/review.md": "---\ndescription: Review a file\n---\nReview $1 and be $2. All: $ARGUMENTS\n"},
     "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-skill-command", "process": True, "args": MODEL + ["-p", "/skill:demo now"], "files": RESOURCES, "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-edit-tool", "process": True, "args": MODEL + ["-p", "edit it"], "files": {"project/data.txt": "alpha\nbeta\n"},
     "turns": [{"tool": {"name": "edit", "arguments": {"path": "data.txt", "edits": [{"oldText": "beta", "newText": "gamma"}]}}}, {"text": "Edited."}], "steps": []},
    {"name": "print-edit-missing", "process": True, "args": MODEL + ["-p", "edit it"], "files": {"project/data.txt": "alpha\n"},
     "turns": [{"tool": {"name": "edit", "arguments": {"path": "data.txt", "edits": [{"oldText": "zeta", "newText": "gamma"}]}}}, {"text": "Failed."}], "steps": []},
    {"name": "print-write-tool", "process": True, "args": MODEL + ["-p", "write it"],
     "turns": [{"tool": {"name": "write", "arguments": {"path": "sub/new.txt", "content": "fresh\n"}}}, {"text": "Written."}], "steps": []},
    {"name": "print-bash-fail", "process": True, "args": MODEL + ["-p", "run it"],
     "turns": [{"tool": {"name": "bash", "arguments": {"command": "echo out; echo err >&2; exit 4"}}}, {"text": "Failed."}], "steps": []},
    {"name": "print-unknown-tool", "process": True, "args": MODEL + ["-p", "run it"],
     "turns": [{"tool": {"name": "nosuch", "arguments": {}}}, {"text": "Hm."}], "steps": []},
    {"name": "print-bad-args", "process": True, "args": MODEL + ["-p", "read it"],
     "turns": [{"tool": {"name": "read", "arguments": {"offset": "x"}}}, {"text": "Hm."}], "steps": []},
    {"name": "print-untrusted-project", "process": True, "args": MODEL + ["-p", "/proj hello"],
     "files": {"project/.pi/prompts/proj.md": "Project prompt: $1\n", "project/.pi/settings.json": json.dumps({"defaultThinkingLevel": "high"})},
     "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-approved-project", "process": True, "args": MODEL + ["--approve", "-p", "/proj hello"],
     "files": {"project/.pi/prompts/proj.md": "Project prompt: $1\n", "project/.pi/settings.json": json.dumps({"defaultThinkingLevel": "high"})},
     "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-default-trust", "process": True, "args": MODEL + ["-p", "/proj hello"],
     "files": {"project/.pi/prompts/proj.md": "Project prompt: $1\n", "home/.pi/agent/settings.json": json.dumps({"defaultProjectTrust": "always"})},
     "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-saved-trust", "process": True, "args": MODEL + ["-p", "/proj hello"],
     "files": {"project/.pi/prompts/proj.md": "Project prompt: $1\n", "home/.pi/agent/trust.json": json.dumps({"<root>": True, "<root>/project": False})},
     "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-saved-parent-trust", "process": True, "args": MODEL + ["-p", "/proj hello"],
     "files": {"project/.pi/prompts/proj.md": "Project prompt: $1\n", "home/.pi/agent/trust.json": json.dumps({"<root>": True})},
     "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-session-reuse", "process": True, "before": [MODEL + ["--session-id", "abc-reuse", "-p", "first"]],
     "args": MODEL + ["--session-id", "abc-reuse", "-p", "second"], "turns": [{"text": "one"}, {"text": "two"}], "steps": []},
    {"name": "print-session-partial", "process": True, "before": [MODEL + ["--session-id", "abc-partial", "-p", "first"]],
     "args": MODEL + ["--session", "abc-par", "-p", "second"], "turns": [{"text": "one"}, {"text": "two"}], "steps": []},
    {"name": "print-fork", "process": True, "before": [MODEL + ["--session-id", "abc-fork", "-p", "first"]],
     "args": MODEL + ["--fork", "abc-fork", "-p", "second"], "turns": [{"text": "one"}, {"text": "two"}], "steps": []},
    {"name": "print-session-missing", "process": True, "args": MODEL + ["--session", "nothing-here", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-fork-conflict", "process": True, "args": MODEL + ["--fork", "x", "--no-session", "-p", "hi"], "steps": []},
    {"name": "print-session-dir", "process": True, "args": MODEL + ["--session-dir", "sessions-here", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-image-file", "process": True, "args": MODEL + ["-p", "@pixel.png", "what is it"],
     "files": {"project/pixel.png": base64.b64decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4z8AAAAMBAQDJ/pLvAAAAAElFTkSuQmCC")}, "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-missing-file", "process": True, "args": MODEL + ["-p", "@nope.txt", "x"], "steps": []},
    {"name": "print-bad-thinking", "process": True, "args": MODEL + ["--thinking", "huge", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-unknown-flag", "process": True, "args": MODEL + ["--frobnicate", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-bad-mode", "process": True, "args": MODEL + ["--mode", "yaml", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-api-key", "process": True, "args": MODEL + ["--api-key", "sk-other", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    # A bare id listed by several providers: the sole authenticated one wins,
    # otherwise the id is ambiguous (upstream resolveCliModel).
    {"name": "print-bare-authed", "process": True, "args": ["--model", "gpt-5", "-p", "hi"], "turns": [{"text": "ok"}], "steps": []},
    {"name": "print-bare-unauthed", "process": True, "args": ["--model", "gpt-5", "-p", "hi"], "env": {"OPENAI_API_KEY": ""}, "steps": []},
    {"name": "print-bare-two-authed", "process": True, "args": ["--model", "gpt-5", "-p", "hi"], "env": {"OPENROUTER_API_KEY": "sk-x", "AZURE_OPENAI_API_KEY": "sk-y"}, "steps": []},
    {"name": "print-no-context", "process": True, "args": MODEL + ["-nc", "-ns", "-p", "hi"], "files": RESOURCES, "turns": [{"text": "ok"}], "steps": []},
]

# Exercise the same editor handoffs through the fullscreen terminal lifecycle.
external_editor = next(case for case in SCENARIOS if case["name"] == "external-editor")
SCENARIOS.append({**external_editor, "name": "external-editor-fullscreen", "args": MODEL + ["--tui-mode", "fullscreen"]})
