// Actual pinned Agent methods and full loop helpers; only the provider is a fixture.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {stripTypeScriptTypes} from 'node:module';
import {createInitialSystemMessage,getCurrentSystemMessage,getCurrentSystemPrompt,getCurrentTools,getToolStateChanges,toToolDeclaration,normalizeContext} from '../../pi-mono/packages/ai/src/utils/transcript.ts';
import {getDefaultStreamFn} from '../../pi-mono/packages/agent/src/stream-fn.ts';
import {Compile} from '../build/schema-reference/node_modules/typebox/build/compile/index.mjs';
import {Value} from '../build/schema-reference/node_modules/typebox/build/value/index.mjs';
const validationSource=fs.readFileSync('../pi-mono/packages/ai/src/utils/validation.ts','utf8');
const validationBody=stripTypeScriptTypes(validationSource.slice(validationSource.indexOf('const validatorCache ='))).replace(/^export /gm,'');
const validateToolArguments=new Function('Compile','Value',validationBody+';return validateToolArguments;')(Compile,Value);
const loopSource=fs.readFileSync('../pi-mono/packages/agent/src/agent-loop.ts','utf8');
const entries=loopSource.slice(loopSource.indexOf('export async function runAgentLoop('),loopSource.indexOf('function createAgentStream('));
const loopBody=stripTypeScriptTypes(entries+loopSource.slice(loopSource.indexOf('async function runLoop('))).replace(/^export /gm,'');
const {runAgentLoop,runAgentLoopContinue}=new Function('getCurrentTools','getToolStateChanges','toToolDeclaration','normalizeContext','validateToolArguments','getDefaultStreamFn',loopBody+';return {runAgentLoop,runAgentLoopContinue};')(getCurrentTools,getToolStateChanges,toToolDeclaration,normalizeContext,validateToolArguments,getDefaultStreamFn);
const source=fs.readFileSync('../pi-mono/packages/agent/src/agent.ts','utf8');
const body=stripTypeScriptTypes(source.slice(source.indexOf('function defaultConvertToLlm('))).replace(/^export /gm,'');
const {Agent}=new Function('createInitialSystemMessage','getCurrentSystemMessage','getCurrentSystemPrompt','toToolDeclaration','getDefaultStreamFn','runAgentLoop','runAgentLoopContinue',body+';return {Agent};')(createInitialSystemMessage,getCurrentSystemMessage,getCurrentSystemPrompt,toToolDeclaration,getDefaultStreamFn,runAgentLoop,runAgentLoopContinue);

const trace=[];
let calls=0,agent;
const first=provider=>{assert.equal(provider,'unknown');trace.push('ka');return 'fixture-a';};
const second=provider=>{assert.equal(provider,'unknown');trace.push('kb');return 'fixture-b';};
const missing=provider=>{assert.equal(provider,'unknown');trace.push('kn');return undefined;};
const failed=provider=>{assert.equal(provider,'unknown');trace.push('ke');throw Error('key lookup failed');};
const assistant=()=>({role:'assistant',content:[{type:'text',text:'answer'}],api:'unknown',provider:'unknown',model:'unknown',stopReason:'stop',timestamp:0});
const streamFn=async(model,context,options)=>{
 trace.push('p'+(options.apiKey===undefined?'-':options.apiKey.replace('fixture-','')));
 const initial=calls++===0;
 if(initial)agent.getApiKey=second;
 const message=initial?{...assistant(),content:[{type:'toolCall',id:'call',name:'echo',arguments:{}}],stopReason:'toolUse'}:assistant();
 return {result:async()=>message,async *[Symbol.asyncIterator](){yield {type:'done',reason:message.stopReason,message};}};
};
agent=new Agent({streamFn,initialState:{tools:[{name:'echo',label:'Echo',description:'Echo',parameters:{type:'object'},execute:async()=>({content:[],details:null})}]}});
assert.equal(agent.getApiKey,undefined);
agent.getApiKey=first;
await agent.prompt('first');
assert.equal(agent.getApiKey,second);
await agent.prompt('next');
agent.getApiKey=undefined;
await agent.prompt('cleared');
agent.getApiKey=missing;
await agent.prompt('no key');
const before=calls;
agent.getApiKey=failed;
await agent.prompt('failure');
assert.equal(calls,before);assert.equal(agent.state.errorMessage,'key lookup failed');
agent.getApiKey=second;
await agent.prompt('recovered');
assert.equal(agent.state.errorMessage,undefined);
assert.equal(trace.join(';')+';','ka;pa;ka;pa;kb;pb;p-;kn;p-;ke;kb;pb;');
console.log('PASS upstream Agent API-key callback capture, clearing, missing keys and recovery');
