// Actual pinned Agent methods and full loop helpers; only the provider is a fixture.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {stripTypeScriptTypes} from 'node:module';
import {createInitialSystemMessage,getCurrentSystemMessage,getCurrentSystemPrompt,getCurrentTools,getToolStateChanges,toToolDeclaration,normalizeContext} from '../../pi-mono/packages/ai/src/utils/transcript.ts';
import {getDefaultStreamFn} from '../../pi-mono/packages/agent/src/stream-fn.ts';
import {Compile} from '../build/schema-reference/node_modules/typebox/build/compile/index.mjs';
import {Value} from '../build/schema-reference/node_modules/typebox/build/value/index.mjs';
const validationSource=fs.readFileSync('../pi-mono/packages/ai/src/utils/validation.ts','utf8');
const validationBody=stripTypeScriptTypes(validationSource.slice(validationSource.indexOf('const validatorCache ='))).replace(/^export /gm,'');
const validateToolArguments=new Function('Compile','Value',validationBody+';return validateToolArguments;')(Compile,Value);
const loopSource=fs.readFileSync('../pi-mono/packages/agent/src/agent-loop.ts','utf8');
const entries=loopSource.slice(loopSource.indexOf('export async function runAgentLoop('),loopSource.indexOf('function createAgentStream('));
const loopBody=stripTypeScriptTypes(entries+loopSource.slice(loopSource.indexOf('async function runLoop('))).replace(/^export /gm,'');
const {runAgentLoop,runAgentLoopContinue}=new Function('getCurrentTools','getToolStateChanges','toToolDeclaration','normalizeContext','validateToolArguments','getDefaultStreamFn',loopBody+';return {runAgentLoop,runAgentLoopContinue};')(getCurrentTools,getToolStateChanges,toToolDeclaration,normalizeContext,validateToolArguments,getDefaultStreamFn);
const source=fs.readFileSync('../pi-mono/packages/agent/src/agent.ts','utf8');
const body=stripTypeScriptTypes(source.slice(source.indexOf('function defaultConvertToLlm('))).replace(/^export /gm,'');
const {Agent}=new Function('createInitialSystemMessage','getCurrentSystemMessage','getCurrentSystemPrompt','toToolDeclaration','getDefaultStreamFn','runAgentLoop','runAgentLoopContinue',body+';return {Agent};')(createInitialSystemMessage,getCurrentSystemMessage,getCurrentSystemPrompt,toToolDeclaration,getDefaultStreamFn,runAgentLoop,runAgentLoopContinue);

const defaults={transport:'auto',toolExecution:'parallel'};
const configured={sessionId:'configured',thinkingBudgets:{minimal:1,low:2,medium:3,high:4},transport:'websocket',maxRetryDelayMs:123,toolExecution:'sequential'};
const future={transport:'sse',toolExecution:'parallel'};
const keys=['sessionId','thinkingBudgets','transport','maxRetryDelayMs','toolExecution'];
const settings=value=>Object.fromEntries(keys.filter(key=>value[key]!==undefined).map(key=>[key,value[key]]));
const requests=[];
let agent;
const assistant=()=>({role:'assistant',content:[{type:'text',text:'answer'}],api:'unknown',provider:'unknown',model:'unknown',stopReason:'stop',timestamp:0});
const streamFn=async(model,context,options)=>{
 requests.push(structuredClone(settings(options)));
 const first=requests.length===1;
 if(first) Object.assign(agent,{sessionId:undefined,thinkingBudgets:undefined,transport:'sse',maxRetryDelayMs:undefined,toolExecution:'parallel'});
 const message=first?{...assistant(),content:[{type:'toolCall',id:'call',name:'echo',arguments:{}}],stopReason:'toolUse'}:assistant();
 return {result:async()=>message,async *[Symbol.asyncIterator](){yield {type:'done',reason:message.stopReason,message};}};
};
agent=new Agent({streamFn,initialState:{tools:[{name:'echo',label:'Echo',description:'Echo',parameters:{type:'object'},execute:async()=>({content:[],details:null})}]}});
assert.deepEqual(settings(agent),defaults);
Object.assign(agent,configured);
assert.deepEqual(settings(agent),configured);
await agent.prompt('first');
assert.deepEqual(settings(agent),future);
await agent.prompt('next');
assert.deepEqual(requests,[configured,configured,future]);
console.log('PASS upstream Agent setting defaults, assignment, clearing and per-run capture');
