#!/bin/sh
# Regression checks for the native-value migration; not full-port acceptance.
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"
python3 scripts/check-proofs.py
sh scripts/build-pure.sh tests/library-types.bend build/test-library-types
build/test-library-types
for suite in transcript event-stream json native-agent; do
  sh "tests/$suite.sh"
done
for threads in 1 4; do
  PI_BEND_TEST_THREADS="$threads" sh tests/runtime-concurrency.sh
done
for suite in resolver_request_check http_url_check http_url_request_check url_special_host_check url_opaque_path_check url_input_check url_serialize_check url_path_check url_authority_check url_scheme_port_check url_host_input_check url_host_check idna_domain_check idna_domain_policy_check idna_label_check idna_label_rules_check idna_ace_check idna_properties_check idna_contextj_check idna_bidi_check u32_table_check idna_mapping_check idna_prepare_check stable_sort_check unicode_normalization_check punycode_check url_ipv6_check url_ipv4_check url_percent_check string_split_check http_buffered_framing_check http_chunked_upload_check http_buffered_body_check http_request_head_check http_response_reader_check http_response_stream_check http_response_policy_check http_framing_fields_check http_body_sse_check http_chunked_body_check http_chunk_size_check http_fixed_body_check http_content_length_check http_head_check http_field_check http_status_check http_line_check responses_auth_check copilot_headers_check request_headers_check headers_check http_header_check provider_headers_check calendar_check http_date_syntax_check random_check timer_delay_check provider_retry_error_check provider_retry_check provider_retry_policy_check responses_params_check responses_request_check responses_policy_check provider_env_check error_body_check serial_resource_check responses_wire_check openai_sse_reader_check openai_sse_json_check sse_reader_check sse_stream_vectors sse_decoder_vectors sse_chunks_vectors line_decoder_vectors utf8_vectors typed_do_shadow static_sum_layout record_vectors constrained_sampling_vectors tool_declaration_vectors tool_state_vectors tool_history_vectors model_types thinking_options_check strict_schema_check grammar_input_check responses_tools_check responses_content_check responses_assistant_check responses_stream_content_check responses_stream_state_check responses_terminal_check responses_terminal_named responses_messages_check responses_stream_contracts_named provider_text_check json_repair_check partial_json_check json_parse_check text_signature_check responses_ids_check context_estimate_check context_estimate_named base_options_check transform_images_check transform_replay_check transform_tool_results_check transform_normalization_check model_metadata_vectors model_cost_vectors agent_types provider_option_types loop_config_types tool_preparation_types tool_result_message tool_batch_vectors tool_batch_sequential_check tool_batch_parallel_check turn_completion_check tool_changes_check turn_preparation_check main_loop_check loop_entry_check default_stream_check loop_stream_check agent_state_check agent_runtime_check agent_listeners_check agent_failure_check agent_loop_config_check agent_hooks_check agent_run_check agent_owner_check agent_prompt_check agent_queues_check tool_selection_vectors before_tool_decision_vectors turn_update_vectors tool_result_vectors validation_primitives_vectors primitive_coercion_vectors schema_type_coercion_vectors f64_remainder_vectors schema_check schema_multiple_check schema_conditional_check unique_items_check schema_convert_check schema_container_check schema_builder_check schema_object_policy_check schema_string_check uri_component_check schema_references_check normalization_check recursive_coercion_check plain_validation_check validation_errors_check; do
  python3 "tests/$suite.py"
done
# Full absolute-URL native emission currently exceeds the installed compiler's
# memory guard. Keep JS coverage here; isolated-candidate native checks are
# recorded separately rather than silently adopting an experimental compiler.
python3 tests/url_absolute_check.py --js-only
python3 tests/url_absolute_wpt_check.py --js-only
python3 scripts/test-inventory.py
