#!/bin/sh
# Regression checks for the native-value migration; not full-port acceptance.
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"
sh scripts/build-pure.sh tests/library-types.bend build/test-library-types
build/test-library-types
for suite in transcript event-stream json native-agent; do
  sh "tests/$suite.sh"
done
for threads in 1 4; do
  PI_BEND_TEST_THREADS="$threads" sh tests/runtime-concurrency.sh
done
for suite in static_sum_layout record_vectors constrained_sampling_vectors tool_declaration_vectors tool_state_vectors tool_history_vectors model_types thinking_options_check strict_schema_check grammar_input_check responses_tools_check responses_content_check responses_assistant_check responses_stream_content_check responses_stream_state_check responses_messages_check responses_conversion_named provider_text_check json_repair_check partial_json_check json_parse_check text_signature_check responses_ids_check constrained_sampling_named context_estimate_check context_estimate_named base_options_check transform_images_check transform_replay_check transform_tool_results_check transform_normalization_check model_metadata_vectors model_cost_vectors agent_types provider_option_types loop_config_types tool_preparation_types tool_result_message tool_batch_vectors tool_batch_sequential_check tool_batch_parallel_check turn_completion_check tool_changes_check turn_preparation_check main_loop_check loop_entry_check default_stream_check loop_stream_check agent_state_check agent_runtime_check agent_listeners_check agent_failure_check agent_loop_config_check agent_hooks_check agent_run_check agent_owner_check agent_prompt_check agent_queues_check tool_selection_vectors before_tool_decision_vectors turn_update_vectors tool_result_vectors validation_primitives_vectors primitive_coercion_vectors schema_type_coercion_vectors f64_remainder_vectors schema_check schema_multiple_check schema_conditional_check unique_items_check schema_convert_check schema_container_check schema_builder_check schema_object_policy_check schema_string_check uri_component_check schema_references_check normalization_check recursive_coercion_check plain_validation_check validation_errors_check; do
  python3 "tests/$suite.py"
done
python3 scripts/test-inventory.py
