import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { strict as assert } from "node:assert";
import { ScrollView } from "/home/agent/code/pi-mono/packages/tui/src/components/scroll-view.ts";
import type { Component } from "/home/agent/code/pi-mono/packages/tui/src/tui.ts";
assert.equal(createHash("sha256").update(readFileSync("/home/agent/code/pi-mono/packages/tui/src/components/scroll-view.ts")).digest("hex"), "76dfd9f8a88cabc064f0652b83f16a945fbc988c9fe7c0423a4cd796907ef77d");
const child: Component = { render: () => ["one", "two"], invalidate: () => {} };
const view = new ScrollView(child, { follow: "end", primary: true, scrollbarHideDelayMs: 10 });
const report = (label: string) => console.log(`${label}:${view.scrollTop}:${view.isFollowingEnd}:${(view as any).contentHeight}/${view.viewportHeight}:${view.isScrollbarVisible}:${view.getContentWidth(6)}`);
view.updateLayout(6, 3, () => {});
report("initial");
console.log(`unused1:${view.scrollBy(-2)}`);
report("back2");
console.log(`unused2:${view.scrollBy(-3)}`);
report("back3");
console.log(`unused3:${view.scrollBy(10)}`);
report("forward10");
view.scrollTo(3, {disableFollow: true});
report("suppressed");
view.updateLayout(7, 3, () => {});
report("grown");
view.scrollToEnd();
report("end");
view.scrollToStart();
report("start");
view.setScrollbar("always");
report("always");
view.setScrollbar("auto");
view.scrollBy(1);
report("auto-active");
await new Promise(resolve => setTimeout(resolve, 30));
report("auto-hidden");
