"""Test-only fixtures from pi's pinned TypeBox dependency; no production bridge."""
import base64
import hashlib
import io
import json
from pathlib import Path
import subprocess
import tarfile
import urllib.request

VERSION = '1.3.27'
INTEGRITY = 'zu+jc1pcy4UiNThxikUr36f0Rybk9PEeCg/NE6adeWr/SKsdNO4EzZHYRDlv2YCVAfj3Odq3dESSo/jNyoBXzA=='


def fixtures(root: Path):
    """Return tagged own-property trees generated by the actual schema builders."""
    cache = root / 'build' / f'typebox-{VERSION}.tgz'
    if not cache.exists():
        blob = urllib.request.urlopen(
            f'https://registry.npmjs.org/typebox/-/typebox-{VERSION}.tgz', timeout=30
        ).read()
    else:
        blob = cache.read_bytes()
    if base64.b64encode(hashlib.sha512(blob).digest()).decode() != INTEGRITY:
        raise ValueError('TypeBox archive differs from pi-mono lockfile SHA-512')
    cache.write_bytes(blob)
    target = root / 'build' / f'typebox-{VERSION}'
    target.mkdir(exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(blob)) as archive:
        archive.extractall(target, filter='data')
    package = target / 'package' / 'build'
    source = '''
const {Type} = await import(process.argv[1]);
const {System} = await import(process.argv[2]);
function encode(v) {
  if(v===undefined) return ['undefined'];
  if(v===null) return ['null'];
  if(typeof v==='boolean') return ['boolean',v];
  if(typeof v==='number') { const b=Buffer.alloc(8); b.writeDoubleBE(v); return ['number',b.toString('hex')]; }
  if(typeof v==='string') return ['string',Array.from(v,c=>c.codePointAt(0))];
  if(typeof v==='function') return ['callable',1];
  if(typeof v==='symbol') return ['symbol',1];
  if(typeof v==='bigint') return ['bigint'];
  if(Array.isArray(v)) return ['array',v.map(encode)];
  const fields=Object.getOwnPropertyNames(v).map(k=>[k,encode(v[k]),Object.getOwnPropertyDescriptor(v,k).enumerable]);
  const symbols=Object.getOwnPropertySymbols(v).map((k,i)=>[i,encode(v[k])]);
  return ['object',fields,symbols];
}
const inputs=[];
for (const enumerableKind of [false,true]) {
  System.Settings.Set({enumerableKind});
  inputs.push(Type.Object({}));
  inputs.push(Type.Object({path:Type.String(),limit:Type.Optional(Type.Number({default:0}))},
    {additionalProperties:false,description:undefined}));
  inputs.push(Type.Object({'10':Type.Boolean(),'2':Type.Optional(Type.String()),'a':Type.Array(Type.String())}));
  inputs.push(Type.Object({value:Type.Union([Type.Literal('a'),Type.Null()])},
    {description:'quoted " value',default:{nested:[undefined,NaN,-0]},execute:()=>{},[Symbol('custom')]:1}));
  inputs.push(Type.Object({}, {properties:{override:Type.String()},required:['override'],type:'custom'}));
  inputs.push(Type.Optional(Type.String({description:undefined})));
}
System.Settings.Reset();
console.log(JSON.stringify(inputs.map(v=>({input:encode(v),json:JSON.stringify(v)}))));
'''
    return json.loads(subprocess.check_output([
        'node', '--input-type=module', '-e', source,
        (package / 'index.mjs').as_uri(), (package / 'system' / 'index.mjs').as_uri(),
    ], text=True))
