const upstream=process.env.PI_MONO_ROOT!;
const {stream}=await import(`${upstream}/packages/ai/src/api/anthropic-messages.ts`);
const {getModel}=await import(`${upstream}/packages/ai/src/compat.ts`);
const {normalizeContext}=await import(`${upstream}/packages/ai/src/utils/transcript.ts`);
const mode=process.argv[2] || 'basic';
const model = getModel('anthropic','claude-opus-5');
const tool = {name:'lookup',description:'Look up a value',parameters:{type:'object',properties:{value:{type:'string'}},required:['value']}};
const system={role:'system',content:'You are helpful.',toolsAdded:[tool],timestamp:1};
const user={role:'user',content:'Use the tool',timestamp:2};
const usage={input:0,output:0,cacheRead:0,cacheWrite:0,totalTokens:0,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}};
const assistant={role:'assistant',content:[{type:'thinking',thinking:'reasoning',thinkingSignature:'signature'},{type:'toolCall',id:'toolu_1',name:'lookup',arguments:{value:'42'}}],api:'anthropic-messages',provider:'anthropic',model:'claude-opus-5',usage,stopReason:'toolUse',timestamp:3};
const result={role:'toolResult',toolCallId:'toolu_1',toolName:'lookup',content:[{type:'text',text:'found'}],isError:false,timestamp:4};
const context=normalizeContext({messages:mode==='replay'?[system,user,assistant,result]:[system,user]});
let payload:any;
await stream(model,context,{apiKey:'test-key',cacheRetention:mode==='cache'?'short':'none',...(mode==='adaptive'?{thinkingEnabled:true,effort:'high',temperature:1,toolChoice:'auto'}:{}),onPayload:(value)=>{payload=value;throw new Error('captured')}}).result();
console.log(JSON.stringify(payload));
