"""Generate immutable normalization tables from pinned Unicode 17 data.

Downloaded source/test data stays in the ignored build cache. Production tables
contain only Unicode-derived constants and require no Python or external codec.
"""
import argparse
from collections import defaultdict
from functools import cache
import hashlib
import json
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    'UnicodeData.txt': '2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c',
    'DerivedNormalizationProps.txt': '71fd6a206a2c0cdd41feb6b7f656aa31091db45e9cedc926985d718397f9e488',
    'NormalizationTest.txt': '5019ffd530751a741900c849c0e010332f142a3612234639bd200b82138a87db',
}

def source(name):
    path = ROOT / 'build/unicode-17' / name
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(urlopen('https://www.unicode.org/Public/17.0.0/ucd/' + name, timeout=30).read())
    raw = path.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == SOURCES[name], f'Unicode source hash mismatch: {name}'
    return raw.decode('utf-8')


def properties():
    classes, decompositions = {}, {}
    for line in source('UnicodeData.txt').splitlines():
        fields = line.split(';')
        code = int(fields[0], 16)
        if int(fields[3]):
            classes[code] = int(fields[3])
        if fields[5] and not fields[5].startswith('<'):
            decompositions[code] = tuple(int(part, 16) for part in fields[5].split())
    excluded = set()
    for line in source('DerivedNormalizationProps.txt').splitlines():
        fields = [part.strip() for part in line.split('#')[0].split(';')]
        if len(fields) < 2 or fields[1] != 'Full_Composition_Exclusion':
            continue
        limits = [int(part, 16) for part in fields[0].split('..')]
        excluded.update(range(limits[0], limits[-1] + 1))
    @cache
    def decomposed(code):
        return tuple(value for part in decompositions[code] for value in decomposed(part)) if code in decompositions else (code,)
    entries = {}
    for code in sorted(classes.keys() | decompositions.keys()):
        parts = decomposed(code) if code in decompositions else ()
        entries[code] = (classes.get(code, 0), tuple((part, classes.get(part, 0)) for part in parts))
    compositions = defaultdict(dict)
    for code, parts in decompositions.items():
        if len(parts) == 2 and code not in excluded:
            first, second = parts
            assert second not in compositions[first]
            compositions[first][second] = str(code)
    return entries, compositions


def tree(entries):
    if not entries:
        return 'Table.Empty{}', 0
    middle = len(entries) // 2
    key, value = entries[middle]
    left, lh = tree(entries[:middle])
    right, rh = tree(entries[middle+1:])
    assert abs(lh-rh) <= 1
    return f'Table.Branch{{{key}, {value},\n{left},\n{right}}}', max(lh, rh) + 1


def table(entries):
    items = sorted(entries.items())
    assert len({key for key, _ in items}) == len(items)
    root, height = tree(items)
    return f'Table.Table{{{height}n, {root}}}'


def generate():
    entries, compositions = properties()
    values = {code: 'Data.Property{' + str(ccc) + ', ' + ''.join(f'Data.Point{{{part}, {cls}}} <> ' for part, cls in parts) + 'Nil{}}' for code, (ccc, parts) in entries.items()}
    source_text = '''# Generated by scripts/generate-unicode-normalization.py; do not edit.
# Unicode 17.0.0 data, Unicode License V3; see unicode-LICENSE.txt.
import Base
import ./u32-table.bend as Table
import ./unicode.bend as Data

'''
    source_text += 'def properties() -> Table.Table<Data.Property>:\n  ' + table(values).replace('\n', '\n  ') + '\n\n'
    source_text += 'def compositions() -> Table.Table<Table.Table<U32>>:\n  ' + table({key: table(value) for key, value in compositions.items()}).replace('\n', '\n  ') + '\n\n'
    source_text += 'def tables() -> Data.Tables: Data.Tables{properties(), compositions()}\n'
    return source_text, len(entries), sum(len(value) for value in compositions.values())


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result, count, pairs = generate()
    path = ROOT / 'packages/runtime/src/unicode-17-normalization.bend'
    if args.check:
        assert path.read_text() == result, 'generated normalization tables are stale'
    else:
        path.write_text(result)
    print(f'Unicode 17: {count} properties, {pairs} composition pairs, {len(result.encode())} source bytes')

if __name__ == '__main__':
    main()
