"""Pinned Unicode17 General_Category classes: letters (L*), numbers (N*),
punctuation (P*) and symbols (S*), the `\\p{L}`, `\\p{N}`, `\\p{P}` and
`\\p{S}` of JavaScript regular expressions."""
import argparse,hashlib,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent))
from decision_tree import decision_tree
from urllib.request import urlopen
ROOT=Path(__file__).resolve().parents[1]
DIGEST='2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c'
def source():
 path=ROOT/'build/unicode-17-display/UnicodeData.txt'
 if not path.exists():
  path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(urlopen('https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt',timeout=30).read())
 raw=path.read_bytes();assert hashlib.sha256(raw).hexdigest()==DIGEST
 return raw.decode()
def classes():
 values=[0]*0x110000;first=None
 for line in source().splitlines():
  row=line.split(';');cp=int(row[0],16);category=row[2]
  if row[1].endswith(', First>'):first=cp;continue
  lo=first if row[1].endswith(', Last>') else cp;first=None
  values[lo:cp+1]=[{'L':1,'N':2,'P':3,'S':4}.get(category[0],0)]*(cp-lo+1)
 return values
def generate():
 values=classes();runs=[(0,values[0])]+[(cp,values[cp]) for cp in range(1,len(values)) if values[cp]!=values[cp-1]]
 nodes,root=decision_tree('categoryBelow',runs,'code',str,'U32',[('code','U32')])
 return f'''# Generated by scripts/generate-category-unicode.py from Unicode17.0.0.
# Unicode License V3; see unicode-LICENSE.txt. Constant decisions (plain definitions) allocate no table.
# General_Category class of a scalar: 1 = Letter (L*), 2 = Number (N*),
# 3 = Punctuation (P*), 4 = Symbol (S*), 0 = other.
import Base

# {len(runs)} runs.
{nodes}
def category(+code: U32) -> U32:
  {root}
def isLetter(+code: U32) -> Bool: U32.is_eq(category(code),1)
def isNumber(+code: U32) -> Bool: U32.is_eq(category(code),2)
def isPunctuation(+code: U32) -> Bool: U32.is_eq(category(code),3)
def isSymbol(+code: U32) -> Bool: U32.is_eq(category(code),4)
'''
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args();out=ROOT/'packages/runtime/src/unicode-17-category.bend';text=generate()
 if args.check:assert out.read_text()==text,'category data changed'
 else:out.write_text(text)
 print('Unicode17 letter, number, punctuation and symbol classes generated and checked')
