"""Generate compact scalar-equivalence cycles from Unicode 17 simple folding."""
from collections import defaultdict
import hashlib
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
URL = 'https://www.unicode.org/Public/17.0.0/ucd/CaseFolding.txt'
SHA256 = 'ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183'


def mappings():
    path = ROOT / 'build/unicode-17/CaseFolding.txt'
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(urlopen(URL, timeout=30).read())
    raw = path.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == SHA256
    result = {}
    for line in raw.decode().splitlines():
        fields = line.split('#')[0].split(';')
        if len(fields) > 2 and fields[1].strip() in ['C', 'S']:
            result[int(fields[0], 16)] = int(fields[2], 16)
    assert all(result.get(value, value) == value for value in result.values())
    return result


def generate():
    groups = defaultdict(set)
    for source, target in mappings().items():
        groups[target].update([source, target])
    assert max(map(len, groups.values())) == 4
    cycles = {code: values[(i + 1) % len(values)] for group in groups.values()
              for values in [sorted(group)] for i, code in enumerate(values)}
    keys = sorted(cycles)
    segments, index = [], 0
    while index < len(keys):
        first = last = keys[index]
        offsets = [(cycles[first] - first) % 2**32] * 2
        index += 1
        if index < len(keys) and keys[index] == first + 1:
            last = keys[index]
            offsets[1] = (cycles[last] - last) % 2**32
            index += 1
        while index < len(keys) and keys[index] == last + 1 and (cycles[keys[index]] - keys[index]) % 2**32 == offsets[(keys[index] - first) % 2]:
            last = keys[index]
            index += 1
        segments.append((first, last, *offsets))
    # Validate compression across every included code, not a sample.
    expanded = {code: (code + offsets[(code-first) % 2]) % 2**32
                for first, last, *offsets in segments for code in range(first, last + 1)}
    assert expanded == cycles

    def tree(rows):
        if not rows:
            return 'Table.Empty{}'
        mid = len(rows) // 2
        row = rows[mid]
        return ('Table.Branch{' + str(row[0]) + ', Segment{' + ','.join(map(str, row)) + '},\n  '
                + tree(rows[:mid]) + ',\n  ' + tree(rows[mid+1:]) + '}')

    generated = ('# Generated by scripts/generate-case-fold.py; Unicode License V3, see unicode-LICENSE.txt.\n'
                 f'# {len(cycles)} participating scalars, {len(segments)} parity-affine segments.\n'
                 f'def segments() -> Table.Table<Segment>:\n  Table.Table{{{len(segments).bit_length()}n, {tree(segments)}}}\n')
    path = ROOT / 'packages/runtime/src/case-fold.bend'
    text = path.read_text()
    prefix, rest = text.split('# BEGIN GENERATED UNICODE TABLE\n')
    _, suffix = rest.split('# END GENERATED UNICODE TABLE')
    path.write_text(prefix + '# BEGIN GENERATED UNICODE TABLE\n' + generated + '# END GENERATED UNICODE TABLE' + suffix)
    print(f'{len(cycles)} scalars, {len(segments)} segments')


if __name__ == '__main__':
    generate()
