"""Generate default Unicode17 lowercase and contextual property tables."""
import sys
import argparse, importlib.util
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'scripts'))
from decision_tree import decision_tree
spec=importlib.util.spec_from_file_location('ucd',ROOT/'scripts/generate-regex-unicode.py')
ucd=importlib.util.module_from_spec(spec);spec.loader.exec_module(ucd)

def data():
    archive=ucd.source();mapping={};props=[0]*0x110000
    for row in ucd.records(archive,'UnicodeData.txt'):
        if row[13]:mapping[int(row[0],16)]=[int(row[13],16)]
    for row in ucd.records(archive,'SpecialCasing.txt'):
        if not row[4]:mapping[int(row[0],16)]=[int(x,16) for x in row[1].split()]
    for span,name,*_ in ucd.records(archive,'DerivedCoreProperties.txt'):
        bit={'Cased':1,'Case_Ignorable':2}.get(name,0)
        if bit:
            for cp in ucd.points(span):props[cp]|=bit
    return mapping,props

def decision(name,values):
    spans=[(0,values[0])]+[(cp,value) for cp,value in enumerate(values[1:],1) if values[cp-1]!=value]
    return decision_tree(name+'Below',spans,'code',str,'U32',[('code','U32')])

def generate(check=False):
    mapping,props=data();delta=[0]*0x110000
    expansions={cp:out for cp,out in mapping.items() if len(out)!=1}
    assert expansions=={0x130:[0x69,0x307]},expansions
    for cp,out in mapping.items():
        if len(out)==1:delta[cp]=(out[0]-cp)&0xffffffff
    result='# Generated from pinned Unicode17 UCD by scripts/generate-case-map.py.\n# Unicode License V3; see unicode-LICENSE.txt.\nimport Base\n\n'
    nodes,root=decision('properties',props)
    result+=nodes+'\ndef properties(+code: U32) -> U32:\n  '+root+'\n\n'
    nodes,root=decision('delta',delta)
    result+=nodes+'\ndef delta(+code: U32) -> U32:\n  '+root+'\n'
    target=ROOT/'packages/runtime/src/unicode-17-case-map.bend'
    if check:assert target.read_text()==result,'regenerate case mapping data'
    else:target.write_text(result)
    print(f'{len(mapping)} lowercase mappings; Cased and Case_Ignorable classification; {len(result)} generated bytes')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');generate(p.parse_args().check)
