"""Generate Unicode17 grapheme properties; production segmentation stays in Bend."""
import sys
import argparse
import hashlib
from pathlib import Path
from urllib.request import urlopen

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'scripts'))
from decision_tree import decision_tree
SOURCES={
 'auxiliary/GraphemeBreakProperty.txt':'d6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89',
 'DerivedCoreProperties.txt':'24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08',
 'emoji/emoji-data.txt':'2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b',
 'auxiliary/GraphemeBreakTest.txt':'e2d134d2c52919bace503ebb6a551c1855fe1a1faec18478c78fff254a1793ec',
}
CLASSES=['Other','CR','LF','Control','Extend','ZWJ','Regional_Indicator','Prepend','SpacingMark','L','V','T','LV','LVT']

def source(name):
 path=ROOT/'build/unicode-17'/name
 if not path.exists():
  path.parent.mkdir(parents=True,exist_ok=True)
  path.write_bytes(urlopen('https://www.unicode.org/Public/17.0.0/ucd/'+name,timeout=30).read())
 raw=path.read_bytes();assert hashlib.sha256(raw).hexdigest()==SOURCES[name],name
 return raw.decode()

def rows(name):
 for line in source(name).splitlines():
  fields=[x.strip() for x in line.split('#')[0].split(';')]
  if len(fields)<2:continue
  bounds=[int(x,16) for x in fields[0].split('..')]
  yield bounds[0],bounds[-1],fields[1:]

def properties():
 values=[0]*0x110000
 for lo,hi,fields in rows('auxiliary/GraphemeBreakProperty.txt'):
  values[lo:hi+1]=[CLASSES.index(fields[0])]*(hi-lo+1)
 for lo,hi,fields in rows('emoji/emoji-data.txt'):
  if fields[0]=='Extended_Pictographic':
   for cp in range(lo,hi+1):values[cp]|=16
 for lo,hi,fields in rows('DerivedCoreProperties.txt'):
  if fields[0]=='InCB':
   value={'Consonant':1,'Extend':2,'Linker':3}[fields[1]]*32
   for cp in range(lo,hi+1):values[cp]|=value
 return values

def generate():
 values=properties();compressed=values.copy()
 # Hangul LV/LVT alternate every28 scalars; arithmetic avoids798 range changes.
 for cp in range(0xac00,0xd7a4):
  assert values[cp]==(12 if (cp-0xac00)%28==0 else 13)
  compressed[cp]=0
 ranges=[(128,compressed[128])]
 for cp in range(129,len(compressed)):
  if compressed[cp]!=compressed[cp-1]:ranges.append((cp,compressed[cp]))
 # Check compression over the complete scalar domain, not selected examples.
 restored=compressed[:128]+[value for i,(_,value) in enumerate(ranges) for _ in range(ranges[i+1][0]-ranges[i][0] if i+1<len(ranges) else len(compressed)-ranges[i][0])]
 assert restored==compressed
 nodes,root=decision_tree('lookupBelow',ranges,'code',str,'U32',[('code','U32')])
 return '''# Generated by scripts/generate-grapheme.py; Unicode17.0.0, Unicode License V3.
# See unicode-LICENSE.txt. Low4 bits GCB, bit4 Extended_Pictographic, bits5..6 InCB.
# Balanced decisions (plain definitions) allocate no property table per input string.
import Base

'''+f'# {len(ranges)} property runs outside ASCII and algorithmic Hangul.\n'+nodes+'\ndef lookup(+code: U32) -> U32:\n  '+root+'\n'

if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
 path=ROOT/'packages/runtime/src/unicode-17-grapheme.bend';text=generate()
 if args.check:assert path.read_text()==text,'generated grapheme properties changed'
 else:path.write_text(text)
 source('auxiliary/GraphemeBreakTest.txt')
 print('Unicode17 grapheme properties generated and exhaustively checked')
