"""Generate immutable Unicode 17 properties used by IDNA label validation."""
import argparse
import hashlib
import importlib.util
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    'DerivedBidiClass.txt': '4867b4b7f0731ed1bfcd34cc6251211ff1542541fce0734b6fbda139ee80b3a4',
    'DerivedJoiningType.txt': 'f39ebe974825d6736aee15582250307aa532b2cfab3caf3f86bd23fddc9c5c4d',
}
BIDI = 'L R AL EN AN ES CS ET ON BN NSM B S WS LRE LRO RLE RLO PDF LRI RLI FSI PDI'.split()
JOINING = dict(zip('ULRDCT', ['NonJoining','LeftJoining','RightJoining','DualJoining','JoinCausing','Transparent']))
ALIASES = {'Left_To_Right':'L', 'Right_To_Left':'R', 'Arabic_Letter':'AL', 'European_Terminator':'ET', 'Non_Joining':'U'}

def source(name):
    path = ROOT / 'build/unicode-17' / name
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(urlopen('https://www.unicode.org/Public/17.0.0/ucd/extracted/'+name, timeout=30).read())
    raw = path.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == SOURCES[name], name
    return raw.decode('utf-8')

def property_values(name, allowed):
    text = source(name)
    values = [None] * 0x110000
    # Broad @missing defaults precede narrower script-specific defaults. Explicit
    # assignments override both, regardless of where they occur in the file.
    defaults = [line.split('@missing:')[1] for line in text.splitlines() if '@missing:' in line]
    explicit = [line.split('#')[0] for line in text.splitlines() if line.split('#')[0].strip()]
    for line in defaults + explicit:
        bounds, value = [part.strip() for part in line.split(';')]
        limits = [int(part,16) for part in bounds.split('..')]
        value = ALIASES.get(value,value)
        assert value in allowed
        values[limits[0]:limits[-1]+1] = [value] * (limits[-1]-limits[0]+1)
    assert None not in values
    return values

def generate():
    spec = importlib.util.spec_from_file_location('normalization', ROOT/'scripts/generate-unicode-normalization.py')
    data = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(data)
    bidi = property_values('DerivedBidiClass.txt', BIDI)
    joining = property_values('DerivedJoiningType.txt', JOINING)
    marks, ccc = bytearray(0x110000), bytearray(0x110000)
    first = None
    for line in data.source('UnicodeData.txt').splitlines():
        fields = line.split(';')
        code = int(fields[0],16)
        if fields[1].endswith(', First>'):
            first = (code,fields[2:5])
            continue
        start = code
        if fields[1].endswith(', Last>'):
            assert first is not None and first[1] == fields[2:5]
            start = first[0]
            first = None
        count = code-start+1
        marks[start:code+1] = bytes([fields[2].startswith('M')]) * count
        ccc[start:code+1] = bytes([int(fields[3])]) * count
    assert first is None
    rows = []
    for code, properties in enumerate(zip(bidi,joining,ccc,marks)):
        if rows and rows[-1][2] == properties:
            rows[-1] = (rows[-1][0],code,properties)
        else:
            rows.append((code,code,properties))
    entries = {}
    for first,last,(direction,joining,ccc,mark) in rows:
        value = f'Data.Properties{{Bidi.{direction}{{}}, Joining.{JOINING[joining]}{{}}, {ccc}, {"True" if mark else "False"}{{}}}}'
        entries[first] = f'Data.Entry{{{last}, {value}}}'
    result = '''# Generated by scripts/generate-idna-properties.py; do not edit.
# Unicode 17.0.0 data, Unicode License V3; see unicode-LICENSE.txt.
import Base
import ./u32-table.bend as Table
import ./idna-properties.bend as Data
import ./unicode-bidi-class.bend as Bidi
import ./unicode-joining-type.bend as Joining

def table() -> Table.Table<Data.Entry>:
  ''' + data.table(entries).replace('\n','\n  ') + '\n'
    return result,len(rows)

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    result,count=generate()
    path=ROOT/'packages/runtime/src/unicode-17-idna-properties.bend'
    if args.check:
        assert path.read_text()==result, 'generated properties are stale'
    else:
        path.write_text(result)
    print(f'Unicode 17 IDNA properties: {count} ranges, {len(result.encode())} bytes')

if __name__=='__main__':
    main()
