"""Pinned Unicode17 terminal-display properties and exact RGI emoji membership."""
import argparse,hashlib,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent))
from decision_tree import decision_tree
from urllib.request import urlopen
ROOT=Path(__file__).resolve().parents[1]
SOURCES={
 'Scripts.txt':('ucd/','9f5e50d3abaee7d6ce09480f325c706f485ae3240912527e651954d2d6b035bf'),
 'ScriptExtensions.txt':('ucd/','ec2107e58825a1586acee8e0911ce18260394ac8b87e535ca325f1ccbeb06bc6'),
 'UnicodeData.txt':('ucd/','2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c'),
 'DerivedCoreProperties.txt':('ucd/','24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08'),
 'EastAsianWidth.txt':('ucd/','ea7ce50f3444a050333448dffef1cadd9325af55cbb764b4a2280faf52170a33'),
 'emoji-sequences.txt':('emoji/','12cc8267dc33cbd11ed32bcf6fc5dc2ad9c7a77bae1bdfba2f41b1b9b3ead8dd'),
 'emoji-zwj-sequences.txt':('emoji/','5b25441daed2322b068c5e70cda522946a4f0274df864445a1965a92e5fc5cad'),
}
def source(name):
 folder,digest=SOURCES[name];path=ROOT/'build/unicode-17-display'/name
 if not path.exists():
  path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(urlopen('https://www.unicode.org/Public/17.0.0/'+folder+name,timeout=30).read())
 raw=path.read_bytes();assert hashlib.sha256(raw).hexdigest()==digest,name
 return raw.decode()
def rows(name):
 for line in source(name).splitlines():
  line=line.split('#')[0].strip()
  if line:yield [x.strip() for x in line.split(';')]
def span(text):
 values=text.split('..');return range(int(values[0],16),int(values[-1],16)+1)
def emoji():
 result=set()
 for name in ['emoji-sequences.txt','emoji-zwj-sequences.txt']:
  for row in rows(name):
   if '..' in row[0]:result.update((cp,) for cp in span(row[0]))
   else:result.add(tuple(int(cp,16) for cp in row[0].split()))
 return result
def properties():
 values=[0]*0x110000;first=None
 for row in rows('UnicodeData.txt'):
  cp=int(row[0],16);category=row[2]
  if row[1].endswith(', First>'):first=cp;continue
  lo=first if row[1].endswith(', Last>') else cp;first=None
  flags=(1 if category.startswith('M') else 0)|(2 if category=='Mc' else 0)|(4 if category in ('Cc','Cs') else 0)|(8 if category=='Cf' else 0)|(1024 if category.startswith('P') else 0)
  values[lo:cp+1]=[flags]*(cp-lo+1)
 for row in rows('DerivedCoreProperties.txt'):
  if row[1]=='Default_Ignorable_Code_Point':
   for cp in span(row[0]):values[cp]|=16
 for row in rows('EastAsianWidth.txt'):
  if row[1] in ('W','F'):
   for cp in span(row[0]):values[cp]|=32
 for row in rows('Scripts.txt'):
  if row[1] in ('Han','Hiragana','Katakana','Hangul','Bopomofo'):
   for cp in span(row[0]):values[cp]|=256
 for row in rows('ScriptExtensions.txt'):
  selected=bool(set(row[1].split()) & {'Hani','Hira','Kana','Hang','Bopo'})
  for cp in span(row[0]):values[cp]=(values[cp]&~256)|(256 if selected else 0)
 for sequence in emoji():
  values[sequence[0]]|=64 if len(sequence)==1 else 128
 # Only punctuation within the CJK break scripts is kept (bit 512).
 values=[(v&~1024)|(512 if v&1024 and v&256 else 0) for v in values]
 return values
def hash_sequence(points):
 h=2166136261
 for cp in points:h=((h^cp)*16777619)&0xffffffff
 return h
def literal(points):return '"'+''.join('\\u{'+format(cp,'x')+'}' for cp in points)+'"'
def generate():
 values=properties();runs=[(0,values[0])]+[(cp,values[cp]) for cp in range(1,len(values)) if values[cp]!=values[cp-1]]
 restored=[value for i,(lo,value) in enumerate(runs) for _ in range((runs[i+1][0] if i+1<len(runs) else len(values))-lo)]
 assert restored==values
 hashes={}
 for sequence in sorted(emoji()):
  if len(sequence)>1:hashes.setdefault(hash_sequence(sequence),[]).append(sequence)
 header='''# Generated by scripts/generate-display-unicode.py from Unicode17.0.0.
# Unicode License V3; see unicode-LICENSE.txt. Constant decisions (plain definitions) allocate no table.
# Bits: Mark=1, SpacingMark=2, Control/Surrogate=4, Format=8,
# Default_Ignorable=16, Wide/Fullwidth=32, singleton RGI_Emoji=64, multi-scalar RGI start=128, CJK break Script_Extensions=256,
# CJK punctuation (General_Category P* with the CJK break Script_Extensions)=512.
import Base
import ./string.bend as Strings

'''
 property_nodes,property_root=decision_tree('propertiesBelow',runs,'code',str,'U32',[('code','U32')])
 emoji_nodes,emoji_root=decision_tree('emojiBelow',sorted(hashes.items()),'hash',lambda choices:' || '.join('Strings.equal(text,'+literal(seq)+')' for seq in choices),'Bool',[('hash','U32'),('text','String')])
 result=header+f'# {len(runs)} property runs; exact membership for {len(emoji())} RGI emoji.\n'+property_nodes+'\ndef properties(+code: U32) -> U32:\n  '+property_root+'\n\ndef emojiHash(text: String,value: U32) -> U32:\n  match text:\n    case SNil{}: value\n    case SCon{char,rest}: emojiHash(rest,U32.mul(U32.xor(value,Char.to_u32(char)),16777619))\n\n'+emoji_nodes+'\ndef emojiCandidates(+hash: U32,+text: String) -> Bool:\n  '+emoji_root+'\n\ndef rgiTail(+char: Char,rest: String) -> Bool:\n  match rest:\n    case SNil{}: U32.is_ne(U32.and(properties(Char.to_u32(char)),64),0)\n    case +rest: Bool.pick(Unit -> Bool,U32.is_ne(U32.and(properties(Char.to_u32(char)),128),0),_ => emojiCandidates(emojiHash(SCon{char,rest},2166136261),SCon{char,rest}),_ => False{})(Unit{})\ndef isRgiEmoji(text: String) -> Bool:\n  match text:\n    case SNil{}: False{}\n    case SCon{char,rest}: rgiTail(char,rest)\n'
 return result
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args();out=ROOT/'packages/runtime/src/unicode-17-display.bend';text=generate()
 if args.check:assert out.read_text()==text,'display data changed'
 else:out.write_text(text)
 print('Unicode17 display properties and exact RGI membership generated and checked')
