"""Pin ICU78 Khmer words and Unicode sets; pack immutable native radix data."""
import argparse, hashlib, importlib.util, json, struct
from pathlib import Path
from urllib.request import urlopen
ROOT=Path(__file__).resolve().parents[1]
URL='https://raw.githubusercontent.com/unicode-org/icu/release-78.3/icu4c/source/data/brkitr/dictionaries/khmerdict.txt'
SHA='87bee2d17cd5148aa36957eb05409eefc124de8ad519b81b789298ef3e60b5d9'

def generate(check=False):
    path=ROOT/'build/icu78-source/khmerdict.txt'
    if not path.exists():path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(urlopen(URL).read())
    data=path.read_bytes();assert hashlib.sha256(data).hexdigest()==SHA
    words=set();root={}
    for line in data.decode('utf-8-sig').splitlines():
        word=line.split('#')[0].strip()
        if not word:continue
        assert all((0x1780<=ord(c)<=0x17ff or ord(c) in (0x200c,0x200d)) for c in word),repr(word)
        words.add(word);node=root
        for char in word:node=node.setdefault(char,{})
        node['']=0
    assert max(map(len,words))<=20  # Therefore at most ICU's 20 prefix candidates.
    output=bytearray();nodes=0
    def pack(node):
        nonlocal nodes
        edges=[]
        for char,child in sorted(node.items()):
            if not char:continue
            label=char
            while '' not in child and len(child)==1 and len(label)<20:
                char,child=next(iter(child.items()));label+=char
            edges.append((label,child))
        for _,child in edges:pack(child)
        output.extend(struct.pack('<BH',node.get('',255),len(edges)))
        for label,_ in reversed(edges):output.append(len(label));output.extend(label.encode('utf-16-le'))
        nodes+=1
    pack(root)
    binary=b'ICUKHM01'+struct.pack('<II',nodes,len(words))+output
    stack=[];offset=16
    for _ in range(nodes):
        cost,count=struct.unpack_from('<BH',binary,offset);offset+=3;children=[]
        for _ in range(count):
            length=binary[offset];offset+=1;label=binary[offset:offset+length*2].decode('utf-16-le');offset+=length*2
            children.append((label,stack.pop()))
        stack.append((cost,children))
    assert offset==len(binary) and len(stack)==1
    restored=set()
    def collect(node,prefix):
        cost,children=node
        if cost==0:restored.add(prefix)
        else:assert cost==255
        for label,child in children:collect(child,prefix+label)
    collect(stack[0],'');assert restored==words
    spec=importlib.util.spec_from_file_location('ucd',ROOT/'scripts/generate-regex-unicode.py');ucd=importlib.util.module_from_spec(spec);spec.loader.exec_module(ucd)
    archive=ucd.source();khmer=set();sa=set();marks=set()
    for span,name,*_ in ucd.records(archive,'Scripts.txt'):
        if name=='Khmer':khmer.update(ucd.points(span))
    for span,name,*_ in ucd.records(archive,'LineBreak.txt'):
        if name=='SA':sa.update(ucd.points(span))
    for row in ucd.records(archive,'UnicodeData.txt'):
        if row[2].startswith('M'):marks.add(int(row[0],16))
    def predicate(name,points):
        checks=['(U32.is_ge(code,%d) && U32.is_le(code,%d))'%(lo,hi) for lo,hi in ucd.ranges(points)]
        return 'def '+name+'(char: Char) -> Bool:\n  match char:\n    case Chr{+code}: '+' || '.join(checks)+'\n'
    native='import Base\nimport ./cjk-dictionary.bend as Dictionary\n\n# Generated by scripts/generate-khmer-dictionary.py; ICU78/Unicode17.\n'
    native+='def decode(bytes: List<&2,U32>) -> Dictionary.Parsed(Dictionary.Trie):\n  match bytes:\n    case '+' <> '.join(map(str,binary[:16]))+' <> rest:\n      Dictionary.records('+str(nodes)+'n,Done{Dictionary.Building{rest,Nil{}}})\n    case _: Fail{Dictionary.InvalidDictionary{}}\n'
    native+='def maxWordLength() -> Nat: '+str(max(map(len,words)))+'n\n'
    native+=predicate('handles',khmer&sa)+predicate('mark',(khmer&sa&marks)|{32})
    license=(ROOT/'packages/runtime/data/icu78-cjk.LICENSE').read_bytes().split(b'\nComplete cjdict.txt source notices:')[0]
    license+=('\nComplete khmerdict.txt source notices:\n'+'\n'.join(line for line in data.decode('utf-8-sig').splitlines() if '#' in line)+'\n').encode()
    manifest={'source':URL,'source_sha256':SHA,'icu':'78.3','unicode':'17.0','entries':len(words),'nodes':nodes,'bytes':len(binary),'sha256':hashlib.sha256(binary).hexdigest(),'max_word_length':max(map(len,words)),'format':'ICUKHM01: magic8,nodeCount:u32le,wordCount:u32le; CJK radix record format with cost0 terminal,255 nonterminal; edge labels capped20','license':'icu78-khmer.LICENSE','unicode_sha256':ucd.SHA}
    files={'packages/runtime/data/icu78-khmer.bin':binary,'packages/runtime/data/icu78-khmer.manifest.json':(json.dumps(manifest,indent=2)+'\n').encode(),'packages/runtime/data/icu78-khmer.LICENSE':license,'packages/runtime/src/khmer-word-data.bend':native.encode()}
    for name,content in files.items():
        target=ROOT/name
        if check:assert target.read_bytes()==content,name
        else:target.write_bytes(content)
    print(f'{len(words)} Khmer words, {nodes} radix nodes, {len(binary)} bytes; exact serialized roundtrip passes')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');generate(p.parse_args().check)
