"""Generate Unicode 17 UTS #46 mapping ranges; no runtime host dependency."""
import argparse
import hashlib
import importlib.util
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    'IdnaMappingTable.txt': '87f05505dc026fdb2bff16132bdc68a8014675836882a9a2b1844540ad3be382',
    'IdnaTestV2.txt': 'beb5d0be20e896189b03209a82fdc34f06351502bbd4b8e2523583fc2954d9cf',
}

def source(name):
    path = ROOT / 'build/unicode-17' / name
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(urlopen('https://www.unicode.org/Public/17.0.0/idna/' + name, timeout=30).read())
    raw = path.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == SOURCES[name], f'IDNA source hash mismatch: {name}'
    return raw.decode('utf-8')


def ranges():
    entries = []
    previous = -1
    for line in source('IdnaMappingTable.txt').splitlines():
        fields = [field.strip() for field in line.split('#')[0].split(';')]
        if len(fields) < 2:
            continue
        bounds = [int(part, 16) for part in fields[0].split('..')]
        first, last = bounds[0], bounds[-1]
        assert first == previous + 1 and first <= last
        previous = last
        status = fields[1]
        assert status in {'valid', 'ignored', 'mapped', 'deviation', 'disallowed'}
        replacement = tuple(int(part, 16) for part in fields[2].split()) if len(fields) > 2 else ()
        assert all(code <= 0x10ffff and not 0xd800 <= code <= 0xdfff for code in replacement)
        if entries and entries[-1][2:] == (status, replacement):
            entries[-1] = (entries[-1][0], last, status, replacement)
        else:
            entries.append((first, last, status, replacement))
    assert previous == 0x10ffff
    return entries


def generate():
    spec = importlib.util.spec_from_file_location('normalization_generator', ROOT / 'scripts/generate-unicode-normalization.py')
    data = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(data)
    entries = ranges()
    values = {}
    for first, last, status, replacement in entries:
        literal = '"' + ''.join('\\u{' + format(code, 'x') + '}' for code in replacement) + '"'
        value = 'Data.' + status.title() + '{' + (literal if status in ['mapped','deviation'] else '') + '}'
        values[first] = f'Data.Entry{{{last}, {value}}}'
    result = '''# Generated by scripts/generate-idna-mapping.py; do not edit.
# Unicode 17.0.0 UTS #46 data, Unicode License V3; see unicode-LICENSE.txt.
import Base
import ./u32-table.bend as Table
import ./idna-mapping-data.bend as Data

def table() -> Table.Table<Data.Entry>:
  ''' + data.table(values).replace('\n','\n  ') + '\n'
    return result, len(entries)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result, count = generate()
    path = ROOT / 'packages/runtime/src/unicode-17-idna-mapping.bend'
    if args.check:
        assert path.read_text() == result, 'generated IDNA mapping is stale'
    else:
        path.write_text(result)
    print(f'Unicode 17 IDNA: {count} ranges, {len(result.encode())} source bytes')

if __name__ == '__main__':
    main()
